### PR TITLE
Fix grammar around variadic function calls

### PR DESCRIPTION
**Pull request by JoshDreamland**
Because 'V' is used to denote variadic functions, but then 'n' is substituted in for later code simplicity, 'V' needs to be treated like 'n' when determining token separation. This change lets `cprime` donate an alternate interpretation of `c`, the token marker character, so this can be detected.

### CODE REVIEW

**Comment by RobertBColton** [comment]
```gml
if z>=other.z3+other.z
 ds_list_add(list,other.z3+other.z)
```
Now correctly parses to:
```cpp
    if(enigma::varaccess_z(int(self))>= enigma::varaccess_z3(int(other))+ enigma::varaccess_z(int(other)))
      ds_list_add(enigma::varaccess_list(int(self)), (enigma::varargs(), enigma::varaccess_z3(int(other))+ enigma::varaccess_z(int(other))));
```

However ```choose(1,2,3);``` in a script in an empty game throws an exception up to LGM but does not crash.

**Comment by RobertBColton** [comment]
```gml
show_message(string(choose(1,2,3)));
```
Becomes;
```cpp
show_message(toString(choose((enigma::varargs(), 1, 2, 3))));
```

```gml
show_message(string(choose(a,b,c)));
```
Becomes:
```cpp
show_message(toString(choose((enigma::varargs(), enigma::varaccess_a(int(self)), enigma::varaccess_b(int(self)), enigma::varaccess_c(int(self))))));
```

**Comment by JoshDreamland** [comment]
No one has merged this, yet. Is there a reason not to?

**Comment by RobertBColton** [comment]
I think we just wanted to fix it as best we could, as in, this is fine to pull, but ```choose(...)``` still doesn't work with numeric literals. All of the games I tested continue to work, and this PR fixes one game that broke because of #1019.

This is problematic because in #1019 I made all the data structure functions variadic, as they are in GMS.
```gml
ds_list_add(items, 1, 1, 2, 3, 4, 4, 4);
```

Meaning we should probably fix the last issue before we make a new release. If you want to do it now and then merge or merge and then do it later, it doesn't matter, just as long as it's fixed before a new release.

**Pull request merged**
