### PR TITLE
Fix `with()` smashing

### PR DESCRIPTION
**Pull request by JoshDreamland**
As noted in #983, there are some visibility issues with the current iterator class that allowed a stacked pointer to be persisted in another object past its lifetime. This caused segfaults when cleaning up after a `with()` execution. This change simplifies that system a bit, and hides those members to make this problem impossible in the future.

I have verified that this change builds on Arch Linux. I have no information on whether it will build on Windows, or whether it will break old games. Robert, if you would, please test it against games that use instance creation code, and games that use `with()` heavily, in addition to the case in #983.

This branch contains #998; merge it, first.

### CODE REVIEW

**Comment by RobertBColton** [comment]
Well I pulled the branch and made sure it actually changed the files, I see iterator is now a class in my local copy. It does not fix #983 however and the minimal example I have with a with() in the create event that calls a script that shows a message and returns 1 still segfaults. The collision memory leak from the iterators however has not returned and the FPS example continues to run great.

**Comment by JoshDreamland** [comment]
Oh my God. I literally made the same mistake in that class' constructor. It should have been `iterator_level(it)`, not `iterator_level(push.it)`. It just rolled off my fingertips and sounded all cutesy. Ugh. Go ahead and pull this again.

**Comment by JoshDreamland** [comment]
Also, please get that diffbase (#998) merged, first, so the diff of this change is useful.

**Comment by RobertBColton** [comment]
I don't understand.

**Comment by RobertBColton** [comment]
I am so sorry I tested originally with the wrong ENIGMA. I have two on my desktop. This does fix the with bug. Let me do some further testing.

**Comment by RobertBColton** [comment]
```
g++ -std=c++11 -I../Additional/i686-w64-mingw32/include -Wall -s -O3 -fno-rtti -fno-exceptions -DPATH_EXT_SET -IPlatforms/Win32/Info -IGraphics_Systems/OpenGL1/Info -IAudio_Systems/OpenAL/Info -ICollision_Systems/Precise/Info -IWidget_Systems/Win32/Info -INetworking_Systems/None/Info -IUniversal_System/Info -I. -IC:/ProgramData/ENIGMA/ -Wall -s -O3 -fno-exceptions  -MMD -MP -c -o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Run/SHELLmain.o SHELLmain.cpp
In file included from SHELLmain.cpp:102:0:
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h: In function 'variant room_0_instancecreate_100001()':
Universal_System/with.h:30:3: error: expected unqualified-id before 'for'
   for (enigma::iterator::with with(enigma::fetch_inst_iter_by_int(x)); \
   ^
Universal_System/with.h:37:31: note: in expansion of macro 'with'
   for (enigma::iterator::with with(enigma::fetch_roominst_iter_by_id(x)); \
                               ^
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:33:3: note: in expansion of macro 'with_room_inst'
   with_room_inst((100001))
   ^
Universal_System/with.h:30:3: error: expected ';' before 'for'
   for (enigma::iterator::with with(enigma::fetch_inst_iter_by_int(x)); \
   ^
Universal_System/with.h:37:31: note: in expansion of macro 'with'
   for (enigma::iterator::with with(enigma::fetch_roominst_iter_by_id(x)); \
                               ^
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:33:3: note: in expansion of macro 'with_room_inst'
   with_room_inst((100001))
   ^
Universal_System/with.h:30:3: error: expected primary-expression before 'for'
   for (enigma::iterator::with with(enigma::fetch_inst_iter_by_int(x)); \
   ^
Universal_System/with.h:37:31: note: in expansion of macro 'with'
   for (enigma::iterator::with with(enigma::fetch_roominst_iter_by_id(x)); \
                               ^
C:/ProgramData/ENIGMA/Preprocessor_Environment_Editable/IDE_EDIT_roomcreates.h:33:3: note: in expansion of macro 'with_room_inst'
   with_room_inst((100001))
   ^
Universal_System/with.h:30:3: error: expected ';' before 'for'
   for (enigma::iterator::with with(enigma::fetch_inst_iter_by_int(x)); \
```

Instance creation code in the room editor now fails to build.

**Comment by JoshDreamland** [comment]
I'm on a roll, today. Okay, fixed.

**Comment by JoshDreamland** [comment]
Merged in diff base; I'll give you guys the weekend to test this out. I'll look over it by sight, as well. I suspect this change can only improve the situation.

**Comment by RobertBColton** [comment]
@JoshDreamland The last commit seems to have fixed the instance creation code. With continues to work as expected and so do several games. This also fixes the bug originally reported in #983 as well. I did notice an issue with LateralGM where the instance creation code is not saving at times, which @TheExDeus did mention before. I'll dig and see if I can file an issue for it with reproducible steps.

**Comment by RobertBColton** [comment]
@JoshDreamland Don't forget #983 is now resolved.

**Pull request merged**
