### PR TITLE
Rebase EGM changes onto Master.

### PR DESCRIPTION
**Pull request by JoshDreamland**
Attempts to re-apply EGM changes to Master. GMX changes made in that branch are not included unless they magically had no conflicts.

### CODE REVIEW

**Comment by RobertBColton** [comment]
@JoshDreamland ah, I just remembered why you had GMX changes in there. The `egmcrap` branch was based on #1479 or else fundies threatened me to merge it into it. If that's true, I am not sure you can necessarily just throw those commits away without replacing them with something else. Regardless, if we want #1479 then we also need to fix its conflicts.

**Comment by fundies** [comment]
@RobertBColton idk wtf going on with this pr it has some sort of ghost.  I don't see any conflicts in my repo when I go to pull it as a new pr to here but updating josh's it just says theres a conflict every time...

**Comment by RobertBColton** [comment]
@fundies look at it in the web editor. It's just whitespace.
Resolve Conflicts
Whitespace Conflicts

**Comment by RobertBColton** [comment]
@fundies Does 563a4a269e065a18254279c0b54daa3a0d9a003e look ok?

**Comment by fundies** [comment]
I fixed it in my branch. Can you just use webui n fix so we can get this merged

**Pull request closed without merging**
