### PR TITLE
flipped = true in OGL will make it right side up

### PR DESCRIPTION
**Pull request by time-killer-games**
fixes upside down screen_save and screen_save_part

### CODE REVIEW

**Comment by time-killer-games** [comment]
Well i thought this would fix it but I just tested it and nothing changed. No flipping happened vertically or horizontally... ?

**Comment by RobertBColton** [comment]
What you are trying to fix is actually #658, because the screen functions are reading from the default framebuffer object. "Surfaces" are called framebuffer objects in OpenGL. When you don't use surfaces/fbos in OpenGL, you still have one for the primary display. The way to fix it is actually much deeper than that, but I don't recall all of the specifics. However, if you can get the default fbo and the surface function fbos the right way up, then it will fix everything, including your issues with the screen_save functions.

**Comment by time-killer-games** [comment]
@RobertBColton this was fundies idea anyway so nag him to do the rest of this. I'd rather proceed with Windows UTF-8 support.

**Comment by RobertBColton** [comment]
Alright, I've begun working on the easier/cleaner way of fixing this in #1343. This brings some of the missing functions to Direct3D as well, and also allows the user to easily add their own functions using the new `draw_getpixels` function.

Thanks for attempting this regardless TKG, it is needing fixed.

**Pull request closed without merging**
