### PR TITLE
Fix Sprite Texture Subimage Index Modulo

### PR DESCRIPTION
**Pull request by RobertBColton**
This fixes a regression caused by #1937 where the `sprite_get_texture` function no long returns the texture of the subimage modulo the sprite subimage count. I agree with the behavior of GM here because there is no use case for requesting the texture of a subimage that's not in a sprite, except to do this modulo behavior for animation. I've amended the draw test to also provide coverage for this functionality which will first fail before the patch is applied, so the bot will post a before and after.

The solution I chose here was to just add an accompanying `ModSubimage` to the sprite class that works with `GetTexture` using the old `get_usi` helper logic for modulo. We could honestly just combine `ModSubimage` into `GetTexture` because as I said above, there is no other use case for passing out of bounds subimage indexes. This also means the universal sprite code now depends on the instance system, rather than the graphics system sprite code depending on the instance system.

>The sub-image (frame) of the sprite to draw (image_index or -1 correlate to the current frame of animation in the object).
https://docs.yoyogames.com/source/dadiospice/002_reference/drawing/drawing%20sprites%20and%20backgrounds/draw_sprite.html

This specifically fixes the [Bloom and Glow example](https://enigma-dev.org/edc/games.php?game=67) from the EDC games. The torch flames are textured with a sprite indexed by a custom counter variable that is unbounded. GM 8.1 and GMSv1.4 both modulo the provided subimage index to the subimage count.
| Master | Pull |
|--------|------|
|Bloom and Glow Master|Bloom and Glow Pull|

### CODE REVIEW

**Comment by RobertBColton** [comment]
Ok, the bot has shown ENIGMA master is broken, it should be 231231 in the first row and 123123 in the second. Now I will apply the patch that fixes the problem and the bot should post the correct image.

**Comment by fundies** [comment]
This one test has gotten bit conflated. We might be better off separating this so future people can understand wtf broke and why.

**Comment by RobertBColton** [comment]
@fundies sure but let's just fix what's broke first, I still have to fix the surfaces regression yet.

@JoshDreamland ok, now the bot is displaying the correct updated image diff with the modulo subimage indexes.

**Review by JoshDreamland — APPROVED** [review]

**Comment by fundies** [comment]
> @fundies sure but let's just fix what's broke first, I still have to fix the surfaces regression yet.

no big deal, I just wanted to note that we keep adding stuff to this test and its gotten a bit messy. It's not a priority but it is something we should consider going forward.

**Pull request merged**
