### PR TITLE
Return a string from file_text_readln instead of void

### PR DESCRIPTION
**Pull request by RobertBColton**
@time-killer-games pointed out in #1136 that it would be useful to do this. It was possible to change this in a backwards-compatible way. I agreed, because it does make the code shorter and idiomatic with Java and C#, so I decided to just do it.

I fixed the indentation in the header to align the function signatures after their return types using spaces. I know ENIGMA doesn't really have a styleguide, but I've seen this used elsewhere in ENIGMA. Not sure how @JoshDreamland feels about this, but since he wrote this file, it seems to me this may be his style. I think it makes the source easier to read. However, it can make some trivial changesets, i.e. adding a new function, much larger than they need to be if all the function signatures need realigned.

I had to actually fix `file_text_eof` too because it was returning 1 line later than all of the other GameMaker versions. In fact, this function is the only reason we need to actually read ahead, so `feof` reports compatibly.

# Test Case
```gml
var file;
file = file_text_open_read("file_text_readln.txt");

show_message("(" + string(file_text_read_real(file)) + ")");
show_message(string(file_text_eoln(file)));
show_message("(" + string(file_text_read_string(file)) + ")");
show_message(string(file_text_eoln(file)));
show_message("(" + string(file_text_read_string(file)) + ")");
file_text_readln(file);
show_message(string(file_text_eoln(file)));
show_message("(" + string(file_text_read_real(file)) + ")");
show_message("(" + string(file_text_read_real(file)) + ")");
show_message("(" + string(file_text_read_string(file)) + ")");
show_message("(" + string(file_text_read_string(file)) + ")");
show_message("(" + string(file_text_read_real(file)) + ")");
file_text_readln(file);

var line1, line12, line2, line3;
line1 = file_text_read_string(file);
line12 = file_text_read_string(file);
line13 = file_text_readln(file);
show_message(string(file_text_eof(file)));
line2 = file_text_readln(file);
show_message(string(file_text_eof(file)));
line3 = file_text_readln(file);
show_message(string(file_text_eof(file)));

show_message(string(string_length(line1)) + ":" + string(line1));
show_message(string(string_length(line12)) + ":" + string(line12));
show_message(string(string_length(line13)) + ":" + string(line13));
show_message(string(string_length(line2)) + ":" + string(line2));
```

# file_text_readln.txt
```text
1 2 3
4 5 6
line1
line2
line3

```

# Results
| GameMaker: Studio v1.4.1773 | Game Maker 8.0 | Game Maker 5.3 A | ENIGMA  |
|-----------------------------|----------------|------------------|---------|
| (1)                         | (1)            | (1)              | (1)     |
| 0                           | 0              | Unknown function              | 0       |
| ( 2 3)                      | (2 3)          | ( 2 3)           | ( 2 3)  |
| 1                           | 1              | Unknown function              | 1       |
| ()                          | ()             | ()               | ()      |
| 0                           | 0              | Unknown function              | 0       |
| (4)                         | (4)            | (4)              | (4)     |
| (5)                         | (5)            | (5)              | (5)     |
| ( 6)                        | (6)            | ( 6)             | ( 6)    |
| ()                          | ()             | ()               | ()      |
| (0)                          | (0)             | Error reading read. and (0)   | (-1)      |
| 0                           | 0              | 0                | 0       |
| 1                           | 1              | 1                |  0      |
| 1                           | 1              | 1                |  1      |
| 5:line2                     | 5:line1        | 5:line2          | 5:line1 |
| 0:                          | 0:             | 0:               | 0:      |
| 2:                          | 0:0            | 0:0              | 1:      |
| 7:line3                     | 0:0            | 0:0              | 6:line2 |

My changes make ENIGMA behave the same as GMS, however, likely because I am using MSYS2, it has Unix, not Windows, line endings. The result of this is that the above test case shows 5,0,2,7 for GMS and 5,0,1,6 for ENIGMA. `file_text_read_string` should not consume the line feed but leave it in the buffer to be consumed by `file_text_readln`, it simply returns the contents of the buffer up to the line feed. `file_text_readln` consumes the entire buffer up to the first line feed and returns it.

### CODE REVIEW

**Comment by fundies** [comment]
I put a .clang-format file in with enigma you can use it's not perfect but you can use it with vscode to get a consistent style,

**Comment by time-killer-games** [comment]
I think I found what could be part of a better solution: https://forum.yoyogames.com/index.php?threads/solved-store-entire-text-file-contents-in-string-gm-8-1.40946/

**Comment by time-killer-games** [comment]
You can use chr(10)+chr(13) added to the end of the line's string to create a new line.

**Comment by RobertBColton** [comment]
@time-killer-games Thanks, but that post only confirms what I've already found. However, it seems strange that you manually had to add the line feeds. As you can see, the strings returned by GMS1.4 for me included the line endings (that's why the length is 2 and 7 for `file_text_readln` return value). My code change in ENIGMA is one shorter because I am using MSYS2 environment to run MinGW64 which gives Unix/Linux style line endings which are just a single character '\n'. Anyway, I'm just confused because the code you had in GMS1.4 in the original post should have worked exactly the same! I don't get it.

**Comment by JoshDreamland** [comment]
Can you format your own test games into 3FG files in the test harness, Robert? I can walk you through it if you need. I'm in the process of adding a lower-impact run() method to work with gTest; I'm hoping that's done before you read this.

**Comment by time-killer-games** [comment]
@RobertBColton are you still going to do what Josh asked you to do back in January in the above post?

**Comment by RobertBColton** [comment]
I can't believe I actually made this pull request. I think I'd like Josh to create the test and I can provide him with more test data from the various GM versions to ensure it's correct.

**Comment by JoshDreamland** [comment]
I thought you *had* a test game. You posted the results of it in the PR description. Why can't you just paste that into a SOG `create.txt`?

**Comment by RobertBColton** [comment]
Josh... the original post is the test game... look it's the text file and the GML to read said text file. Just jam that into a SOG and there you go.

**Comment by RobertBColton** [comment]
Closing in favor of #1717.

**Pull request closed without merging**
