### PR TITLE
Fix SDL Without Breaking Eveything Else

### PR DESCRIPTION
**Pull request by time-killer-games**
Screenshot_20200307_124350

### CODE REVIEW

**Comment by time-killer-games** [comment]
@JoshDreamland you mind restarting Appveyor ci?

**Comment by time-killer-games** [comment]
@JoshDreamland now passing and ready to be merged.

**Comment by time-killer-games** [comment]
@JoshDreamland you forgot to mudge

**Comment by JoshDreamland** [comment]
It sounded as though fundies had something to say.

**Comment by time-killer-games** [comment]
I'm kinda waiting for that.

**Comment by fundies** [comment]
While I have confirmed it does fix the problem. I don't remember exactly why. My best guess is the window scale was 0x0 or 1x1 or something but I can't remember for sure. If you know the actual cause please add it to a comment or the commit message for posterity. Also, quit being such a pain in my ass thanks

**Comment by time-killer-games** [comment]
I believe you are correct, that is the cause. Do you want me to add a code comment explaining this or is adding it to the description of this pr sufficient?

**Comment by JoshDreamland** [comment]
Documenting it here is fine. Go ahead and update the PR description.

**Pull request merged**
