### PR TITLE
Fix game global regressions

### PR DESCRIPTION
**Pull request by RobertBColton**
Taking a second to address a couple of regressions introduced by #1128 that cause Mark Overmar's FPS example to no longer build.

* argument_relative should have been in namespace enigma_user in Universal_System/actions.h
* argument_relative should have been in namespace enigma_user in MotionPlanning/actions.h
* argument_relative should have been in namespace enigma_user in Paths/actions.h
* argument_relative should have been in namespace enigma_user in Collision_Systems/actions.h
* argument_relative should have been in namespace enigma_user in Graphics_Systems/General/actions.h
* place_meeting_inst was using the old guard, just had to rename it to what @fundies changed it to

After these changes, Mark Overmar's FPS example successfully builds again and the gameplay works fine:
Mark Overmars FPS working again

### CODE REVIEW

**Comment by RobertBColton** [comment]
It is in its own header, `GAME_GLOBALS.h` right? Varargs is in `dynamic_args.h`

**Comment by JoshDreamland** [comment]
I believe if you include `GAME_GLOBALS.h`, you will introduce a link error. And it might make sense to have that declaration in a DND-related header, anyway.

**Comment by RobertBColton** [comment]
Why would anybody include `GAME_GLOBALS.h`? Also, how would that fix the other non-action game globals if somebody wanted to include them? Regardless, I don't know about introducing a header just for that one global, actions really only add about 4 globals I think, and one of them is for the caption. So just tell me which of the existing action headers you would want it moved to.

**Comment by fundies** [comment]
I also broke some font_ funcs in fhis commit as they use uint32_t replacing it with unsigned will fix those

**Comment by RobertBColton** [comment]
I'll address those as they come up.

**Pull request merged**
