### PR TITLE
emake doesn't show error finding input file bug fix

### PR DESCRIPTION
**Pull request by medobob1**
Fixes issue #2296
Fixed the issue by making a condition checking if the file name is not empty and that it doesn't exist.

### CODE REVIEW

**Comment by hpgDesigns** [comment]
tested this fix from his branch. It works as far as i can see
image

**Comment by hpgDesigns** [comment]
tested this on his branch. 

image

**Comment by hpgDesigns** [comment]
image

**Comment by hpgDesigns** [comment]
tested this on his branch. works as far as I can see

Screenshot_2023-03-12_15-39-46

**Review by fundies — APPROVED** [review]

**Pull request merged**
