### PR TITLE
Do not write tiles whose backgrounds are missing

### PR DESCRIPTION
**Pull request by JoshDreamland**
I would like the compiler to report these as warnings to the IDE before we merge this pull request. I also have not built nor attempted to run this pull request, so please don't get trigger-happy with the merge button.

### CODE REVIEW

**Comment by faissaloo** [comment]
It compiles, but I can't tell if it fixes the issue.

**Comment by faissaloo** [comment]
Ok, I managed to make the issue appear again and this didn't fix it.

**Comment by JoshDreamland** [comment]
Well, then, it's probably nothing to do with drawing tiles that have missing backgrounds. I'll leave this pull request around because the compiler should arguably be doing this, anyway.

**Comment by RobertBColton** [comment]
Maybe you guys should do #981 since I have the fix for it already.

**Comment by RobertBColton** [comment]
I may as well mention, we just merged #1516, which could be the actual explanation for faissaloo's issue. I should mention though, that some games, specifically SONIGMA GMX, will randomly cut out half of the tiles. I think LateralGM's GMX reader may be the cause because if you just open the project again it goes away.

**Comment by JoshDreamland** [comment]
This is just collecting dust. There are improvements to make on the code, now, if we want to do this, but the benefit seems to have been very little.

**Comment by RobertBColton** [comment]
@faissaloo I want to mention that an issue was fixed in LGM v1.8.46 with regards to what appeared to be missing tiles and instances, but was actually just the sprite transparency property being turned on for GMX/newer projects. The fact that this pull request didn't fix your issue seems to suggest the LGM issue could have been what was affecting you.
https://github.com/IsmAvatar/LateralGM/issues/389

**Comment by faissaloo** [comment]
@RobertBColton I won't be able to test it since I no longer have the setup I had at the time. Though I get the feeling that part of the issue might have just been XMir.

**Comment by RobertBColton** [comment]
Fair enough, I just wanted to make sure and do my due diligence in letting you know. We're here if you happen upon it again anyway!

**Pull request closed without merging**
