### PR TITLE
fix last bug with Cocoa Widgets

### PR DESCRIPTION
**Pull request by time-killer-games**
sorry, I missed something. I forgot to make show_error abort the application when necessary.

### CODE REVIEW

**Comment by time-killer-games** [comment]
@RobertBColton last one ready to mudge for the night

**Comment by time-killer-games** [comment]
@RobertBColton sorry, i forgot just that quickly. my bad.

**Comment by time-killer-games** [comment]
@RobertBColton okay, i also forgot to remove an unused function. But not I'm 10000000% sure its ready for mudge

**Comment by RobertBColton** [comment]
It will say failed, but I know you're just updating your Cocoa widgets, so it's not a big deal for right now.

**Comment by time-killer-games** [comment]
that's fine

**Comment by time-killer-games** [comment]
@RobertBColton I was able to extract the Cocoa Widgets code and put it into it's own Xcode project and it builds. Everything works beautifully, too. Please mudge when you can. Thanks!

[CocoaWidgets.zip](https://github.com/enigma-dev/enigma-dev/files/3012554/CocoaWidgets.zip)

**Pull request merged**
