### PR TITLE
remove win32 ffi vlas

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Comment by RobertBColton** [comment]
@time-killer-games can you test this for him since it affects extensions and I don't really have any laying around?

**Comment by RobertBColton** [comment]
@fundies Whichever is the last of your vla pull requests you should add `-Werror=vla` to prevent anybody from reintroducing vlas again.

**Comment by fundies** [comment]
@JoshDreamland still need this one approved too ...

**Comment by RobertBColton** [comment]
I hope this didn't break extensions or you'll be hearing from tkg shortly.

**Comment by JoshDreamland** [comment]
I wouldn't have approved this if it were possible for it to break anything.

**Comment by RobertBColton** [comment]
Wunderbar then I just didn't want to add anything else broke onto the external handling because of #1511 which I am pretty sure I forced you to cause.

**Comment by time-killer-games** [comment]
@RobertBColton Wow! Wtf why did I not get any notification from your @mention lol well I'm gonna try my extension stuff again and see if this pr has made any positive outcome on our extension system. I hope it will!

**Comment by time-killer-games** [comment]
@RobertBColton unfortunately this pr didn't fix the issue you referenced like I was hoping for. That's a real shame...

**Pull request merged**
