### PR TITLE
Win32 Cleanup Message Pumps

### PR DESCRIPTION
**Pull request by RobertBColton**
Let's continue from #2043 and clean up the rest of the rest of the duplicate message pumps.

### CODE REVIEW

**Comment by RobertBColton** [comment]
@time-killer-games I need you to test something. I want you to test what kind of CPU usage execute_shell has in GM when executing a long running process. Because of #2055 I have discovered that `PeekMessage` will create a loop with much higher CPU usage than `GetMessage` does because the latter uses waiting.

**Comment by RobertBColton** [comment]
Sure maybe if we get to #2055 I can rename it when I introduce a synchronous version of it for certain kinds of loops.

**Comment by time-killer-games** [comment]
@RobertBColton I'm back from the road trip. Bought some bison ribs for Wednesday. Getting to the point here, I can't find the sound code you gave me. Can you use a @mention where the post is so we may continue where we left off? It would be nice if for you gave me a temporary means to contact you at least until this is done so we aren't spamming a flood of GitHub comments.

**Comment by RobertBColton** [comment]
On #2055 Sam

**Pull request merged**
