### PR TITLE
allow fail osx

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Comment by RobertBColton** [comment]
This didn't work because mine was still running.

**Comment by RobertBColton** [comment]
It looks like Travis has been backlogged for a few days so none of the container-based infrastructure works right now:
https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

They just enabled Linux and OSX builds 3 hours ago.

**Comment by fundies** [comment]
I didnt switch us over too containers

**Comment by RobertBColton** [comment]
I may be confusing how this works, but you did remove sudo as being required, but I guess that actually means it's still required because that is the default: https://github.com/enigma-dev/enigma-dev/commit/6b10522917ea334b69a01814e90a12fa9f234752#diff-354f30a63fb0907d4ad57269548329e3L1

Maybe you don't get containers unless you explicitly `sudo: false` to enable it.

**Pull request closed without merging**
