### PR TITLE
Functional OpenGL ES and Bridge Reorganization for Glad

### PR DESCRIPTION
**Pull request by RemoveRusky**
image

### CODE REVIEW

**Comment by RemoveRusky** [comment]
@RobertBColton can you quit hiding like a bitch and point out what I need to separate here to get it merged or better yet do it yourself

**Comment by RemoveRusky** [comment]
u dun?

**Comment by RobertBColton** [comment]
I want to leave a comment here at this point in time to mention something important about the last update. GLES may not work at the moment because I did not test in Android Studio, so the last commit may have broke it. The reason is because that commit pulled the transform changes, and uses `graphics_set_matrix` which passes true for transposing the matrix to the GLSL function. Passing true for transposing a matrix is deprecated in GLES, and that's what took us so long to debug the first time.

**Comment by RobertBColton** [comment]
Closing as stale in favor of #1808, #1799, #1763, #1695.

**Pull request closed without merging**
