### PR TITLE
what a fucking mess pt1

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Comment by faissaloo** [comment]
Why are you removing the d3d_model_*() functions? They were left there intentionally for when d3d_model_save() is implemented. That said, nice work on the game loop.

**Comment by fundies** [comment]
those are duplicates I removed to fix multiple definition errors

**Comment by RobertBColton** [comment]
Nice work, I totally missed that model code in 4b6a5a0

**Comment by JoshDreamland** [comment]
Are you still looking to merge this, fundies?

**Comment by JoshDreamland** [comment]
Okay. Probably better we fix the build before merging.

Also, fundies, while I'd ask you don't format the entire engine again, you created two new files in this PR by separating code into its own directory. Feel free to format those new files.

**Comment by fundies** [comment]
I was under the understaning you were working on your own fix for this in xlib. I can fix this pr if you've given up though.

**Pull request closed without merging**
