### PR TITLE
[LINUX] Hide 640x480 black loading window

### PR DESCRIPTION
**Pull request by time-killer-games**
This is the Linux version of my recent Windows PR

### CODE REVIEW

**Comment by time-killer-games** [comment]
@RobertBColton I have been able to verify that initialize_everything() in fact does NOT make the window visible on Linux currently, so if you want that function to behave like it does on Windows, you will probably want XMapRaised(disp,win); moved to somewhere near the bottom of initialize_everything().

**Comment by RobertBColton** [comment]
No, because then Windows couldn't call initialize_everything(). What you want to do is probably remove the call to XMapRaised altogether, leave the window invisible, and call window_set_visible(true) from where the game start events are fired. Also, to check the compatibility flag to set it visible before or after game start. But this would honestly "just work" if we changed the Xlib platform to use flags for visible, like the Win32 platform does.

**Comment by time-killer-games** [comment]
I'm confused now because the words you used exactly on Google Hangouts were:
> we should have the making visible of the window inside the initialize_everything()

**Comment by RobertBColton** [comment]
Yes, that is exactly correct. Where ``initialize_everything`` makes the window visible is when it calls ``enigma::game_start`` or ``enigma_user::window_default`` depending on if you have at least one room.
https://github.com/enigma-dev/enigma-dev/blob/83bffa133def3f3621f47930a8eb224a53de95ad/ENIGMAsystem/SHELL/Universal_System/loading.cpp#L118

``enigma::game_start`` eventually calls ``gotome`` on the current room struct:
https://github.com/enigma-dev/enigma-dev/blob/b1ef13b320f62b153a6e88284729e806d1f15bfa/ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp#L938

This, in turn, calls ``enigma_user::window_default`` too:
https://github.com/enigma-dev/enigma-dev/blob/b1ef13b320f62b153a6e88284729e806d1f15bfa/ENIGMAsystem/SHELL/Universal_System/roomsystem.cpp#L236

So on Win32 ``window_default`` will set the window visible because isVisible is true and it sets the WS_VISIBLE flag (correct). It's not supposed to force the window to be visible, just set it visible, if it is visible. Our Xlib platform should do basically the same thing, but it's not setup the same way the Win32 one is, in order to use the WS_VISIBLE flag for making the window visible. I am saying we should add a second call explicitly to window_set_visible that sets the window visible based on the compatibility setting, right next to the window_default calls. I can look into this more later and fix it completely, for now, you can just use your workaround locally.

**Comment by time-killer-games** [comment]
I would really like to have that black loading window invisible on all platforms, as soon as it can be done the way you guys can agree on.

**Comment by RobertBColton** [comment]
@time-killer-games This will have to wait until #1122 because Josh is revamping the entire windowing to use less global C++ variables (unrelated to GM globals). I'm waiting to also move `windows.h` include to fix #1119. The problem is all of these variables and header includes create naming conflicts, like not being able to create a script called `CreateFont`. Once @JoshDreamland decides on how he wants to manage the state we can do this fix properly.

**Pull request closed without merging**
