### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by RobertBColton**
Used git filter branch to fix some grammatical mistakes in old commit messages.

### CODE REVIEW

**Comment by fundies** [comment]
dafux point of this mess? Seems like itd only fux all other prs

**Comment by fundies** [comment]
dont't delete my comments. Dafux is the point of this pr as it will only mess up all other prs?

**Comment by JoshDreamland** [comment]
This appears to mess everything up and brings about very little benefit if it doesn't.

**Comment by RobertBColton** [comment]
The diff tool says there's no differences between the branch and a fresh clone of master.
```
$ diff -r enigma-dev enigma-dev2
Only in enigma-dev2/logs: enigma_compile.log
Only in enigma-dev2/logs: enigma_compiler.log
```
It also compiles and seems to work as expected. Again, this was using filter-branch, it's possible I can achieve the same and also keep the same sha commit ids with a rebase.

**Comment by fundies** [comment]
No one cares about those "typos". Also, if you don't stop deleting my comments there's going to be hell to pay. If you're that embarrassed about your words in commits, I have logs of you saying much worse on discord and irc.

**Comment by RobertBColton** [comment]
Alright, I'll find something more productive to work on.

**Pull request closed without merging**
