### PR TITLE
Xlib Display Function Declaration Cleanup

### PR DESCRIPTION
**Pull request by RobertBColton**
In #1886 tkg created a header in the xlib system for some of the internal display resolution getters. He gave them the same name as the user facing functions and a redundant declaration in this header which was the same as the general header.

Simple solution here is I deleted the special header, merged the user facing display functions with his, and corrected the includes. This is not organized like other platforms where the display functions were in the window source, but I decided to leave it this way since it does make it easier to delete the XRandR dependency from xlib.

@time-killer-games in the future, look to see if a general header already includes any functions you are adding and try to mimic the style, conventions, and general structure of other systems.

### CODE REVIEW

**Comment by time-killer-games** [comment]
I do not approve of these changes. The whole point is for this to be standalone and to be put into any project and work without modification. You do not have permission to use my code if you are going to misuse it under the conditions it was contributed.

**Comment by time-killer-games** [comment]
I did that with the display functions on purpose to make that the source and header could be self contained and standalone and could be included in any project and the functions would "just work" out of the box. But if you want to kill that stink bug, go ahead and give it the stank eye, and it will drop dead. :P

**Comment by time-killer-games** [comment]
Yeah I misunderstood what the pull request was doing because I didn't look at the code changes. But now that i think of it, it would be better if we used enigma::x11::disp instead of opening and closing an entirely new display.

If you want, after you merge this, I can make a pull request that does this.

**Comment by RobertBColton** [comment]
Ugh, I see what was going on now, this header was not user directed, it was internal functions that you had the user ones in `XLIBmain.cpp` calling.

@time-killer-games Please remember to put internal functions used across sources into namespace enigma. You used static in the source for the two other helpers, which is fine yes, but then you made these internal helpers with the same name as the user functions and then didn't namespace them. So now you see how that would confuse somebody!

**Comment by RobertBColton** [comment]
@time-killer-games Anyway, yeah, that'd be fine, but understand that display variable is cached. So in other words you would be tying the functions to the display that ENIGMA was originally opened on, not the one it's currently on. That might be something worth testing, I'm not even sure of the correctness of us caching the original display variable that way.

**Comment by time-killer-games** [comment]
No, it's ok! ignore my butthole comments, I deleted them for a reason. This is perfectly fine, honestly.

**Comment by RobertBColton** [comment]
It didn't pass yet.

**Comment by RobertBColton** [comment]
Just fyi I gave this a test in my VirtualBox Ubuntu instance and it seems that XRandR is only adding about 4kb to the final executable size. I tested actually removing XRandR includes and having the user functions return 0 (because somebody apparently made the general platform window functions dependent on them).

**Comment by time-killer-games** [comment]
@RobertBColton please tell me you didn't revert the fact general is dependent on that info. Getting the display width, height, and x/y is 100% necessary to properly center the window on computer with multiple displays.

**Comment by RobertBColton** [comment]
No I didn't change that, but that doesn't mean it shouldn't be changed. Also, for several months now Project Mario and some of my other games do not even center correctly at all on my 4k display. What resolution monitor have you been testing on?

I think in the future we should be more careful about fixing the platform functions. It's much more important that we keep the platforms stable as compared to other systems like widgets. We need to be more reluctant about what changes we accept, and we need to strive for better quality in this area.

**Comment by time-killer-games** [comment]
@RobertBColton if it's not centering properly that's an issue with Xinerama, not our codebase. Some linux distro's have reported it is buggy, but it just depends on the distro. What linux distro are you testing on? Hugar reported thanks to my display changes and the addition of Xinerama, for the very first time in the history of enigma, it centers perfectly for him, where is prior to my changes it never did. I have two monitors 1280x1024 but I've tried them at uneven display settings and no issues.

**Comment by RobertBColton** [comment]
No, I'm talking about on Windows!

**Comment by time-killer-games** [comment]
I didn't change anything on windows lel im sorry you're having trouble?

**Comment by RobertBColton** [comment]
You did, you changed the general platform window center to calculate with the display functions, and that is used on Windows.

**Comment by time-killer-games** [comment]
Uhm, yeah. The only thing i did was make the primary monitor position equal 0,0 which is true for all windows machines.

**Pull request merged**
