### PR TITLE
rwops

### PR DESCRIPTION
**Pull request by fundies**
abstract c file funcs for sdl (the sdl ones do some magic on android)
remove useless "cleandeps" rule from make
fix bug in compiler causing apiswitchboard to always be overwritten

### CODE REVIEW

**Comment by JoshDreamland** [comment]
What magic could SDL be doing outside of `fopen`?

**Comment by fundies** [comment]
It is only fopen but there is no way to get a FILE ptr from rwops to use with c funcs

**Comment by JoshDreamland** [comment]
So they decided the best course of action would be to define their own C library. Okay. What is this interface actually doing for us that just `fopen()` will not?

**Comment by fundies** [comment]
Android hides their files in top secret caves that you need some library that requires a PhD to use to access the real paths of your files. Tldr Google sucks and sdl makes life easier

**Comment by JoshDreamland** [comment]
I'm not a fan of attempting to replace all I/O in the engine with wrappers to allow using SDL's version. If SDL wanted to make life better, they should have provided a way to look up the secret file cave instead of writing their own file library that otherwise adds nothing over stdc.

**Comment by fundies** [comment]
IDC what youre fan of tbh. That's how sdl works so either take it up with them or tell Google to stop their nonsense  on Android. Until then I need to work with the tools I have. Complaing some 3rd party lib is shit don't help

**Comment by RobertBColton** [comment]
You didn't necessarily need to hit so many lines in this diff.

You could have done:
```cpp
using fget = fGet;
```

**Comment by JoshDreamland** [comment]
gg, fundies; you have contained the disease.

I know you don't see the value in it and I recognize that there *is* merit to someone noticing, hey, there's something off about `fOpen`. Maybe this isn't *just* libc `fopen`. But I care more about not accumulating scars as we recognize the shortcomings of an API that is 30+ years old. Especially when the only thing we're actually getting is a proper filename transformation in *one* routine.

**Comment by fundies** [comment]
> gg, fundies; you have contained the disease.
> 
> I know you don't see the value in it and I recognize that there _is_ merit to someone noticing, hey, there's something off about `fOpen`. Maybe this isn't _just_ libc `fopen`. But I care more about not accumulating scars as we recognize the shortcomings of an API that is 30+ years old. Especially when the only thing we're actually getting is a proper filename transformation in _one_ routine.

So, the shitty macros you wanted me use are fuxing me already. This is why I hate using macros. The macros are leaking into <fstream> and giving me errors on android:

``` In file included from /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:20:
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:952:9: error: no matching function for call to 'fseeko'
      if (fseeko(__file_, __width > 0 ? __width * __off : 0, __whence))
          ^~~~~~
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:214:5: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::seekoff' requested here
      basic_filebuf();
      ^
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:1153:14: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::basic_filebuf' requested here
      explicit basic_ifstream(const string& __s, ios_base::openmode __mode = ios_base::in);
               ^
  /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:52:17: note: in instantiation of member function 'std::__ndk1::basic_ifstream<char, std::__ndk1::char_traits<char> >::basic_ifstream' requested here
    std::ifstream from(fname);
                  ^
  /home/greg/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdio.h:202:5: note: candidate function not viable: no known conversion from 'SDL_RWops *' to 'FILE *' (aka '__sFILE *') for 1st argument
  int fseeko(FILE* __fp, off_t __offset, int __whence);
      ^
  In file included from /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:20:
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:954:20: error: no matching function for call to 'ftello'
      pos_type __r = ftello(__file_);
                     ^~~~~~
  /home/greg/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdio.h:203:7: note: candidate function not viable: no known conversion from 'SDL_RWops *' to 'FILE *' (aka '__sFILE *') for 1st argument
  off_t ftello(FILE* __fp);
        ^
  In file included from /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:20:
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:970:9: error: no matching function for call to 'fseeko'
      if (fseeko(__file_, __sp, SEEK_SET))
          ^~~~~~
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:214:5: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::seekpos' requested here
      basic_filebuf();
      ^
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:1153:14: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::basic_filebuf' requested here
      explicit basic_ifstream(const string& __s, ios_base::openmode __mode = ios_base::in);
               ^
  /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:52:17: note: in instantiation of member function 'std::__ndk1::basic_ifstream<char, std::__ndk1::char_traits<char> >::basic_ifstream' requested here
    std::ifstream from(fname);
                  ^
  /home/greg/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdio.h:202:5: note: candidate function not viable: no known conversion from 'SDL_RWops *' to 'FILE *' (aka '__sFILE *') for 1st argument
  int fseeko(FILE* __fp, off_t __offset, int __whence);
      ^
  In file included from /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:20:
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:1002:13: error: no matching function for call to 'fflush'
          if (fflush(__file_))
              ^~~~~~
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:214:5: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::sync' requested here
      basic_filebuf();
      ^
  /home/greg/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/fstream:1153:14: note: in instantiation of member function 'std::__ndk1::basic_filebuf<char, std::__ndk1::char_traits<char> >::basic_filebuf' requested here
      explicit basic_ifstream(const string& __s, ios_base::openmode __mode = ios_base::in);
               ^
  /home/greg/shush-jdi/android/app/jni/../../..//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.cpp:52:17: note: in instantiation of member function 'std::__ndk1::basic_ifstream<char, std::__ndk1::char_traits<char> >::basic_ifstream' requested here
    std::ifstream from(fname);
                  ^
  /home/greg/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdio.h:110:5: note: candidate function not viable: no known conversion from 'SDL_RWops *' to 'FILE *' (aka '__sFILE *') for 1st argument
  int fflush(FILE* __fp);
      ^
  4 errors generated.
  make[2]: *** [/home/greg/shush-jdi/android/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/main//home/greg/shush-jdi/android/app/jni/__/__/__//ENIGMAsystem/SHELL/Platforms/General/POSIX/POSIXfilemanip.o] Error 1
````

**Pull request merged**
