### PR TITLE
[Cocoa] fix for get_color() on esc key

### PR DESCRIPTION
**Pull request by time-killer-games**
Pressing the escape key would close the color picker dialog functions ok, but the game would remain in a frozen modal state. It only happened with pressing escape, and did not happen when pressing the ok or cancel buttons. This pr fixes that issue and treats the escape key as the cancel button by returning -1 like GM. Demo executable demonstrating this has been fixed can be downloaded here: [CocoaWidgets.zip](https://github.com/enigma-dev/enigma-dev/files/3101552/CocoaWidgets.zip)

### CODE REVIEW

**Comment by time-killer-games** [comment]
> Approving the fix because it's small, but otherwise do you notice that you polluted this diff with a bunch of little whitespace changes? That makes it hard for me to tell what you actually changed. If you wanted to remove the whitespace, that should have been sent as a separate pull request.

I am aware of this, but sadly I believe it was editing the file with Xcode that is to blame. It seems to make changes like this for me without my interventions.

**Comment by time-killer-games** [comment]
Josh said since he's traveling out of state you can probably go ahead in merge it, but I'd ask him first if that's what he was implying because I'm not sure 100%.

**Comment by RobertBColton** [comment]
It's fine, Visual Studio Code does that to me. Just remember it for the future and think about it before you go into the files. Regardless, if you had created these dialog sources with XCode to begin with, this would not have happened because it would have removed the whitespace before you had added it. This is why I have switched to VS Code completely.

If you do this for sources with other people on the blame layer/history then I am not likely to approve and merge such future hypothetical changes. I am letting this one slide because you're the only one on the Cocoa dialogs blame/history right now.

**Comment by time-killer-games** [comment]
Thanks!

**Comment by RobertBColton** [comment]
Just fyi in case I haven't already explained. The "blame layer" is me referring to git blame UI features in GitHub's website. For example, this source's blame is here: https://github.com/time-killer-games/enigma-dev/blame/2404d415a69fc464cde0cace95d3b0e09a5d2985/ENIGMAsystem/SHELL/Widget_Systems/Cocoa/dialogs.m

**Comment by time-killer-games** [comment]
Ok, I will keep this in mind.

**Comment by RobertBColton** [comment]
Good. For example, we can see this pull request just split the blame in two.

**Comment by time-killer-games** [comment]
Yes, I understand.

**Pull request merged**
