### PR TITLE
Delete the packages/ folder; no one maintains it.

### PR DESCRIPTION
**Pull request by JoshDreamland**
All it's doing at this point is confusing users.

### CODE REVIEW

**Comment by RobertBColton** [comment]
Uhm, maybe we should keep the desktop entry for ENIGMA? We don't technically have an executable, but we could point it to the CLI maybe? Might possibly want to keep the mime type stuff too to easily register file formats for ENIGMA.

Also I would keep enigma-dev.svg because that is our only copy of that logo in SVG. I would move it over to `Resources/` with the other logos and icons.

**Comment by JoshDreamland** [comment]
The move you requested has been made. There's no point to trying to preserve those other files. They'll remain in our git history for all time.

**Comment by RobertBColton** [comment]
Normally I would complain about what you just did, but I just realized ENIGMA doesn't technically have an exe so you shouldn't be registering MIME types for it anyway. Any modern desktop entry belongs in the IDE's repository or it should be written for ENIGMA's CLI. For that matter, I think the Windows exe we have also belongs in LGM's repository since all it does it look up Java.

I will recommit the ENIGMA SVG you deleted, since it's the only one we have and I totally forgot where it was being kept behind locked doors, under the resources folder.

**Comment by JoshDreamland** [comment]
We can re-commit the SVG when there's actually something that wants to use it. The SVG remains accessible to anyone with a clone of this Git repository.

**Pull request merged**
