### PR TITLE
let's try using a version of glew made in this decade...

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Comment by JoshDreamland** [comment]
This will break existing user installations, too. We will want to post an announcement about this. Let's figure out if there's anything else we need to break, and try to get it out of the way at the same time. Also, I can't remember why I included glxew for Linux; I hope that reason has expired.

**Comment by fundies** [comment]
Yes, it's going to take me a few more tries to even get travis behaving but I believe this is neccessary as the glew we have is from 2008. I don't think we're including any other dependancies anymore other than lodepng.h but I could be wrong.

**Comment by fundies** [comment]
We do need to migrate windows users off the portable zip though and I'm not sure how best to handle that. While msys2 has improved tons it's still more effort than that shitty zip I created lol...

**Comment by fundies** [comment]
msys2 should handle deps for us in the future but I need @RobertBColton to write  migration instructions for windows users

**Comment by RobertBColton** [comment]
Sure, I'm still concerned about the potential of a one-click installer for users, like GMS has. I'm willing to write such an installer. Anything to replace the existing unpalatable zip. However, for some people, like Eclipse IDE, a portable installation that they can easily stick on a thumb drive is an important feature.

I'm in favor of Josh's earlier idea of a web UI you can configure that builds you a special installer based on what extensions you want preconfigured, etc. I can write this using Vue.js

**Comment by fundies** [comment]
I haven't tested but Isee no reason you wouldn't be able to install mys2 to a thumbdrive

**Comment by RobertBColton** [comment]
Closing because I resolved the conflicts in #1226 and I don't have write access to @fundies master anymore.

**Pull request closed without merging**
