### PR TITLE
Graphics Tests Using ImageMagick

### PR DESCRIPTION
**Pull request by RemoveRusky**

### CODE REVIEW

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum

**Comment by RobertBColton** [comment]
Up ur bum
![Hello World](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEYAAAAUCAAAAAAVAxSkAAABrUlEQVQ4y+3TPUvDQBgH8OdDOGa+oUMgk2MpdHIIgpSUiqC0OKirgxYX8QVFRQRpBRF8KShqLbgIYkUEteCgFVuqUEVxEIkvJFhae3m8S2KbSkcFBw9yHP88+eXucgH8kQZ/jSm4VDaIy9RKCpKac9NKgU4uEJNwhHhK3qvPBVO8rxRWmFXPF+NSM1KVMbwriAMwhDgVcrxeMZm85GR0PhvGJAAmyozJsbsxgNEir4iEjIK0SYqGd8sOR3rJAGN2BCEkOxhxMhpd8Mk0CXtZacxi1hr20mI/rzgnxayoidevcGuHXTC/q6QuYSMt1jC+gBIiMg12v2vb5NlklChiWnhmFZpwvxDGzuUzV8kOg+N8UUvNBp64vy9q3UN7gDXhwWLY2nMC3zRDibfsY7wjEkY79CdMZhrxSqqzxf4ZRPXwzWJirMicDa5KwiPeARygHXKNMQHEy3rMopDR20XNZGbJzUtrwDC/KshlLDWyqdmhxZzCsdYmf2fWZPoxCEDyfIvdtNQH0PRkH6Q51g8rFO3Qzxh2LbItcDCOpmuOsV7ntNaERe3v/lP/zO8yn4N+yNPrekmPAAAAAElFTkSuQmCC

**Comment by RobertBColton** [comment]
Up ur bum
Hello World

**Comment by RobertBColton** [comment]
Up ur bum
Hello World

**Comment by RobertBColton** [comment]
Up ur bum
Hello World

**Comment by RobertBColton** [comment]
Up ur bum
Hello World

**Comment by RobertBColton** [comment]
Up ur bum
Hello World

**Comment by RobertBColton** [comment]
Up ur bum
Hello World

**Comment by RobertBColton** [comment]
Graphics fidelity seems to have been compromised by changes in this pull request. Carefully review the following image comparison for anomalies and adjust the change accordingly.
### Expected Results
Expected Graphics Results
### Actual Results
Actual Graphics Results

**Comment by RobertBColton** [comment]
Graphics fidelity seems to have been compromised by changes in this pull request. Carefully review the following image comparison for anomalies and adjust the changeset accordingly.
### Expected Results
Expected Graphics Results
### Actual Results
Actual Graphics Results

**Comment by RobertBColton** [comment]
Graphics fidelity seems to have been compromised by changes in this pull request. Carefully review the following image comparison for anomalies and adjust the changeset accordingly.
### Expected Results
Expected Graphics Results
### Actual Results
Actual Graphics Results

**Comment by RobertBColton** [comment]
Alright, with the `image_compare` fixed to read number of pixels different from ImageMagick's error stream, this is basically working. You can see that I tested it for two separate false positives and have now reset it to properly pass the test. This is basically good to go, unless we want to do something else with it.

**Comment by RemoveRusky** [comment]
I would use screen_save if it actually work but if you remember it has tendency to save things upside down on linux.

**Comment by RobertBColton** [comment]
I am closing this since we are going with #1299 instead since it's easier for us to maintain.

**Pull request closed without merging**
