### PR TITLE
Add function environment_expand_variables()

### PR DESCRIPTION
**Pull request by time-killer-games**
i copy/paste stackoverflow cuz i lazy poophole

### CODE REVIEW

**Comment by time-killer-games** [comment]
@RobertBColton ready for review

**Comment by time-killer-games** [comment]
@JoshDreamland rubbert snub. u halp?

**Comment by JoshDreamland** [comment]
We have code that does this using `%foo%` rather than `${foo}` elsewhere in the compiler:
https://github.com/enigma-dev/enigma-dev/blob/f93a3851fd987d96a7c8d3d381da95528854b29e/CompilerSource/settings.h#L108

**Comment by time-killer-games** [comment]
@JoshDreamland Nice! I had no idea. let

**Pull request closed without merging**
