### PR TITLE
[Windows] Add function execute_shell_for_output()

### PR DESCRIPTION
**Pull request by time-killer-games**

### CODE REVIEW

**Comment by time-killer-games** [comment]
@RobertBColton ready for review.

**Comment by RobertBColton** [comment]
Please ping @JoshDreamland since he was the last one discussing this with you. I am working on other things at the moment. Do this as a general rule of thumb.

**Comment by time-killer-games** [comment]
@RobertBColton josh told me to ping you for windows related stuff. The code doesn't work anyway i just tested it so im going to spend more time on it tmr

**Comment by RobertBColton** [comment]
Ok, sounds good.

**Comment by time-killer-games** [comment]
@JoshDreamland I'm busy with freelance work right now but I'd love to get some assistance on this if I can't figure it out on my own, I've tried show_message(execute_shell_for_output("echo 1")) and it always shows some random foreign characters, I think's because I am doing the wide char version of popen but not the other functions such as fwrite but I can't seem to find the wide char versions of the other functions, is the biggest issue. I really need this to be cross-platform for something I'm working on.

**Comment by JoshDreamland** [comment]
From the Microsoft docs:

> **_wpopen** is a wide-character version of **_popen**; the *path* argument to **_wpopen** is a wide-character string. **_wpopen** and **_popen** behave identically otherwise.

**Comment by time-killer-games** [comment]
Then that's really odd, I wonder why it isn't working then.

**Comment by time-killer-games** [comment]
@JoshDreamland to clarify what isn't working, the command argument works and it executes stuff, but the output doesn't and it returns random crap characters. While stuff is executing and you try to click on or interact with the game window too much, the game will segfault,

**Pull request merged**
