### PR TITLE
Gl3.3 normal matrix

### PR DESCRIPTION
**Pull request by TheExDeus**
Fixes normal matrix and tries to fix wall and floor model. These problems were mentioned by orange451 in topic here: http://enigma-dev.org/forums/index.php?topic=2392

Tested on project mario, 3D lights test, minecraft and several others. Seem to work fine.

Normals for other models (like ellipsoids) are still wrong.

### CODE REVIEW

**Comment by JoshDreamland** [comment]
It seems as though you had a Travis configuration set up in this branch. Is that new? Attempting to view the diff causes browser hiccups.

**Comment by TheExDeus** [comment]
It is in the master as well. From this commit: https://github.com/enigma-dev/enigma-dev/pull/929/commits/64c1d1397128d067d4a8f9bf7e615cc7f8bcf93b

**Comment by JoshDreamland** [comment]
Cool; the diff is useless *and* inaccurate. My opinion stands; just go ahead and merge this when you're ready. Probably a weekend when you have time. I think I'd give some weight to faissaloo's opinion on when that should be, as he seems like the next most active user/contributor.

Please merge #980 into this before you merge upstream.

@faissaloo Are you ready to deal with this branch in your fork?

**Comment by TheExDeus** [comment]
I don't know how many conflicts there will be though. Might not be trivial. But I will try.

**Comment by faissaloo** [comment]
@JoshDreamland Since my changes are restricted to 2 files, only one of which will be needed after the merge (GSstdraw.cpp) it'd be better if I were to refork, re-commit and create another pull request after this is merged rather than deal with the conflicts. It'll be less error prone and less stuff to deal with. I'll keep the existing fork until the merge is done.

**Comment by JoshDreamland** [comment]
What mergetool do you use, Harri? Meld is pretty slick. If you haven't set that up, I can show you how. I'd offer to handle it for you myself, but your understanding of changes in your branch will likely be required, so I'd rather you take a crack at it first.

**Comment by TheExDeus** [comment]
This can now be automatically merged. If someone is interested then testing it before merging would be good. Otherwise Josh can press the green button and we can fix things then.

I tested on several of my projects and everything seems to be working fine. The only issue is that for some reason I cannot compile the .dll with the cmd right now (the makefile doesn't properly run), but it works if the .exe / LGM runs the compilation. Maybe I have just forgotten how I did it via the cmd previously.

**Comment by JoshDreamland** [comment]
Merging it at 5PM on a Sunday is probably a bad idea. I suspect that the shiny green merge button will still be there on Friday. I will hit it, then, if you have not. In the even that the button is gone, I'll merge it manually.

**Comment by TheExDeus** [comment]
It's not like the current master is very stable, so you might as well merge it any other day. There are no guarantees I will have time to fix things in a weekend anyway (like I didn't have the time to do the merge, so that is why I didn't do it Friday or Saturday).

**Comment by faissaloo** [comment]
@TheExDeus  What is exactly the issue with the makefile?

**Comment by TheExDeus** [comment]
It seems there is no issue after all. Previously when I tried "mingw32-make" in ENIGMA root directory for the .dll compilation, it just stopped at one of the first rules. It seems I just had to do a "clean" before compilation.

**Comment by faissaloo** [comment]
I've been having issues with making, this fixed it:  
```
CXXFLAGS += -I -O3 -Wall -g -I./JDI/src -std=c++11
LDFLAGS += -shared -O3 -g
```
However, games don't run, they exit immediately returning 0. If I just compile it the game works though.

**Comment by TheExDeus** [comment]
This branch specifically? What exactly did you have to change?

**Comment by faissaloo** [comment]
Yeah, in the branch /CompilerSource/Makefile is:  
```
CXXFLAGS += -std=c++11 -m32 -Wall -O3 -g -I./JDI/src
LDFLAGS += -shared -m32 -O3 -g
```  

I changed it to:  
```
CXXFLAGS += -I -O3 -Wall -g -I./JDI/src -std=c++11
LDFLAGS += -shared -O3 -g
```

**Comment by faissaloo** [comment]
Ok, I've figured out why it wasn't running with it by running it from the directory, when I run it I get:  
```
[1]    23126 floating point exception (core dumped)  /tmp/egm3728686535922057513.tmp
```

**Comment by faissaloo** [comment]
Ok, it's because of the hashing function is trying to divide by 0 at /usr/include/c++/5/bits/hashtable_policy.h:446  
Universal_System/Extensions/BasicGUI/styles.cpp:55 is the lowest part of ENIGMA calling it.

**Comment by faissaloo** [comment]
Compiling to a file (not just running) with openGL3 causes a segfault.

**Comment by TheExDeus** [comment]
Alright, I'll look into it. Note that this branch exclusively used GL3.3, so I don't know if GL1 even works. And DX doesn't work for sure. So these things need to be checked. Also I only worked and tested on Windows, so Linux might also be broken. Most of the issues should be easy to fix though.

**Comment by faissaloo** [comment]
Both OpenGL 1 and 3 work again after disabling BasicGUI.

**Comment by faissaloo** [comment]
Running in debug mode stops the segfault but the game doesn't change from the first init room that declares global variables and the particle system and I get this in the log repeated hundreds of times:  
```
Program[DEFAULT_SHADER = 0] - Attribute at location 1246712400 not found!
Program[DEFAULT_SHADER = 0] - Attribute at location 1246712400 not found!
Program[DEFAULT_SHADER = 0] - Attribute at location 1717920803 not found!
Program[DEFAULT_SHADER = 0] - Attribute at location 173887055 not found!
Program[DEFAULT_SHADER = 0] - Attribute at location 173887055 not found!
Program[DEFAULT_SHADER = 0] - Attribute at location 1230259013 not found!
Program[DEFAULT_SHADER = 0] - Attribute at location 1230259013 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 538976288 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 538976288 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 538976288 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 1717920803 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 543518313 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 1381253453 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 1397048137 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 1480674655 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 538976288 not found!
Program[DEFAULT_SHADER = 0] - Uniform at location 538976288 not found!
```

**Comment by TheExDeus** [comment]
You seem all over the place. So when disabling the extension, then it doesn't segfault anymore right? So why does debug mode also stopped a segfault? Was it a different segfault?
The uniforms and attributes means this is GL3.3 right? What kind of example are you trying to run?

**Comment by faissaloo** [comment]
Sorry, I'll try to be clearer.  
Disabling the extension fixes the floating point exception, not the segfault.  
The segfault occurs when I try to run [this game](http://s000.tinyupload.com/index.php?file_id=32707495536106634578) though I'm not sure if it's the same issue as the attribute and uniform errors now because I did some tests and those seem to happen whenever you try to draw a sprite (and the sprites don't draw).

**Comment by faissaloo** [comment]
Ok, the segfault is because bck2d is going ridiculously low in load_tiles() (for me it's always 97), the segfault happens right here: https://github.com/enigma-dev/enigma-dev/blob/GL3.3NormalMatrix/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3tiles.cpp#L95  
It's not an issue with all texture switches though, because some texture switches do work.

**Comment by faissaloo** [comment]
Ok, I've figured the segfault out: apparently LGM didn't remove some background that was being used as a tile, so it was left assigned to <no background>, that wasn't properly handled so when it tried to get data from it it was pulling garbage because it never got assigned. After testing this on main branch I can confirm that deleting those fixes #979 too, so I'm guessing this is just a worse version of that.  
  
Ignore the issue I mentioned about sprites not drawing, that's just because apparently my laptop's GPU (intel 3000) doesn't support OpenGL 3.3, it goes away when I use the GTX 750 on my desktop.

**Comment by JoshDreamland** [comment]
That's a crappy circumstance, but debug mode should have been able to catch that. Are we not verifying resource indices we receive in debug mode?

**Comment by faissaloo** [comment]
We are right here, which I'm guessing is why the segfault wasn't happening in debug mode.
https://github.com/enigma-dev/enigma-dev/blob/GL3.3NormalMatrix/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL3/GL3tiles.cpp#L31  
This shouldn't cause a fatal error when debug mode is off though, it should be silently ignored.

**Comment by JoshDreamland** [comment]
Sounds like we need better logging. At any rate, depending on the simplicity of the check, we may want to include it both places. I prefer sentinels over checks. A check is fine, if it's just `(i < len && arr[i])`, but we can't afford to do sanity checking on your resource every time you reference it in a call. That's why debug mode treats things differently, in the first place.

**Comment by TheExDeus** [comment]
So other than that does this work? I really believe this should be merged before much work on ENIGMA can be done. It has LOT of functionality added and bugs fixed. Some of course are also introduced, but they could be fixed.
The hashing bug in BasicGUI has to be fixed, but I have a feeling that error is a lot deeper. Whenever a bug like this appears (there was one in ENIGMA parser as well, I'm sure it is still there) it either means there is some memory corruption in a totally different place or there is a compiler bug.

**Comment by faissaloo** [comment]
Did you fix the issue with OpenGL1 not compiling too (it's nothing too big, I think you just forgot to update the definitions of some stuff) that I mentioned [here](https://github.com/enigma-dev/enigma-dev/pull/929#issuecomment-236360007)?

**Comment by faissaloo** [comment]
Please stop requesting that this gets merged when bugs come up that have already been fixed in this pull until you fix OpenGL 1 compilation and sort the new conflicts out.

**Comment by TheExDeus** [comment]
I already did that once and nothing happened. And as you found the trivial problem then you could of posted a commit on this branch as well, it is not exclusive to me. I just thought duplication of works seems silly, as well as finding "new bugs" that were in fact found months or even years ago and then fixed here. As these bugs were already fixed here it just means more conflicts are generated by fixing them in master.
By no means this branch has less bugs though, so even if it is merged people will find other issues that needs fixing. And I just though doing that on top of this branch makes much more sense then refixing things in master.
I also have merge access, so I guess I should have just merged it in july and so people would have to fix things in master, but as I haven't really been active in ENIGMA development recently I didn't want to force it.
Anyway, I tried the newest ENIGMA and checkout this branch, but sadly LGM crashes on me before I can do anything, so I currently cannot check what is the problem for GL1. I also test only on Windows currently, so I don't know about other platforms.

**Comment by faissaloo** [comment]
I can't fix the problem with OpenGL 1 myself because I don't know which type you were intending to use; which is the mistake and which is intentional. Scroll up through the thread and you'll find the exact error.

**Comment by TheExDeus** [comment]
Try now. The code should be essentially the same as in GL3.3. The only difference is we don't batch in GL1, so matrix updating also doesn't happen only when rendering but all the time. This should actually be changed and the matrix functions should be in Universal, as they are the same for all rendering options. In DX we just need to transpose the matrix when sending it to GPU opposed to GL.

**Comment by RobertBColton** [comment]
@TheExDeus You need the new plugin and to pull some relevant changes from master. I changed the About.ey format for extensions because LGM was interpreting them differently than they were for major systems.
http://enigma-dev.org/forums/index.php?topic=2718.0

**Comment by TheExDeus** [comment]
Then I basically have to merge with master again. Probably a lot of conflicts to fix. I'll try that if I have time, but maybe somebody else wants to do this.

**Comment by RobertBColton** [comment]
Yeah I'm really sorry about that but it did need fixed. It made no sense where major systems used "Name" for the GUI label and then extensions used "Id" I think it caused a lot of conflict and why people kept confusing the two. Judging of course by how every other extension chose to put spaces in one of the two but not the other.

**Comment by JoshDreamland** [comment]
Are there any further objections to me merging this on Friday?

**Comment by JoshDreamland** [comment]
Aldo, all of you use meld, correct? You're talking about merge conflicts like people who don't use meld.

**Comment by faissaloo** [comment]
OpenGL1 is working fully now.

**Comment by JoshDreamland** [comment]
Harri, I went to merge this, but I noticed a few alarming problems in the merge conflicts.

The clearest problem was this:
```C++
    if (surface_exists(id)) {\
      show_error("Attempting to use non-existing surface " + toString(id), false);\
```

But I also noticed from looking at that file that you seem to have replaced the surface array with some other data structure, and you're calling `erase()` on it. I'm not sure how wise that is. I'm hoping the structure you used is the `unordered_map` you included, because otherwise, runtime complexity goes to hell, and using surfaces will break after deleting one.

Still looking.

**Comment by RobertBColton** [comment]
Shouldn't that be wrapped in the debug macro?

**Comment by JoshDreamland** [comment]
It is wrapped in that macro. But it's still wrong. Anyway, I fixed it, and a few other things, during the merge. Someone please make sure I didn't miss anything in the Windows build.

**Comment by faissaloo** [comment]
Why is the libcompileEGMf now set to always compile as 32-bit on Linux instead of just compiling for the native architecture? It means that Java now also has to be run in 32-bit or it won't be able to communicate with the library.

**Comment by JoshDreamland** [comment]
Oh, that change WAS in this pull request? I assumed it was upstream. Yeah, that problem affects me, too. We should probably undo that.

**Comment by TheExDeus** [comment]
> I've confirmed it's not, and I've removed the logic that tries to find an unused IDs. Hash maps are efficient with arbitrarily large keys.
I do use unordered_map. Now though I actually don't favor them as much as I did a year ago. Seeing how few surface resources actually are (or any resource really) a simple std::vector will beat it in both insertion and lookup, as there are rarely more than 1000 elements. And we don't hold references or pointers to them, so reallocation wouldn't probably break them.
Anyway, these are the little things I am learning from in the new engine.

**Comment by RobertBColton** [comment]
Update on this PR, if you see my comment here: https://github.com/enigma-dev/enigma-dev/issues/1031#issuecomment-388423559

I believe the hashing exception was a GCC bug that has been resolved:
https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=61143

It sure looks that way.

**Pull request merged**
