### PR TITLE
use standard compliant varargs

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Comment by fundies** [comment]
> While this makes it compile, it doesn't actually work.

what exactly doesn't work?

**Comment by RobertBColton** [comment]
@fundies `string(...)` duh.

**Comment by fundies** [comment]
> @fundies `string(...)` duh.

give real example u twat

**Comment by RobertBColton** [comment]
`draw_text(0,0,string(fps));`

It will draw "__VA_ARGS__" in the top-left of the screen iirc.

**Comment by time-killer-games** [comment]
Whether this one works yet or not. I don't care. I know he'll get it figured out. fundies has been making a ton of pr's within the past few days, and I couldn't be more happy to see he hasn't given up on the project. Welcome back fundies! :D

**Comment by fundies** [comment]
> `draw_text(0,0,"FPS: " + string(fps));`
> 
> It will give an empty string for the fps value.
> 
> String Conversion Broken

I see it's putting     // Local variables
    var __VA_ARGS__; in the codegen for some reason. I need help from @JoshDreamland to debug this but I know he's gonna be a total cuck about it

**Comment by fundies** [comment]
@RobertBColton can you re-test this for any issues?

**Pull request merged**
