### PR TITLE
Remove duplicate model shape drawing code

### PR DESCRIPTION
**Pull request by RobertBColton**
My goal here is to cut down on duplicate code so that the systems again behave more consistently. There was no reason to maintain 4 separate versions of all of this code.

# Shape Drawing
Because the shape functions for models were generic I simply moved them into a source file in the General/ folder. My idea with redoing those shape functions using the generic model functions a while back was for maintainability. However, this may not be the most performant way to construct them as something closer to the metal, largely due to the lack of efficient data structures in GML. You have the overhead of a function call for every single vertex.

The other problem is that I also made the primitive drawing functions call these on a global model used for batching, which again may not be the most performant but is more maintainable. What I am considering is advancing the vertex buffer functions in all systems to make better use of data structures, and for example, use variadic arguments to also abstract the underlying model class itself. 

@JoshDreamland please review the deleted shape drawing functions because it seems like people modified different versions, and I would like to know which version you think is the best to keep.

# Makefiles
This is also something else that needs to be discussed. It seems we've been just adding a wildcard to pick up all of the sources in the general folder, which has worked for now but may break if we need to do anything more granular.

# Integration
I just want to note that although this may pass Travis CI somebody may have been relying on the inconsistent behavior of a particular system, but I don't think it's likely. However, I have done my best to ensure that several test games continue to work, like I normally do, including the Mark Overmars FPS tutorial.

### CODE REVIEW

**Comment by faissaloo** [comment]
You *could* avoid the overhead of a function call for ever single vertex by having inline versions of the functions for this purpose as well as the normal versions. In fact since vertex functions are usually used in batches it might be useful to inline them in all instances since they'd share alot of commonalities which could lead to better optimisation.

**Comment by JoshDreamland** [comment]
The compiler doesn't really value your opinion on what should be inlined, and I believe we enabled `-flto` for final builds (and if not, we will eventually). That said, we could just change the extension of this file and `#include` it from the file that defines those vertex functions. We could template these methods (or define the vertex puts as macros) to guarantee correct usage. That would increase the likelihood of them being inlined in the object file.

**Comment by RobertBColton** [comment]
@JoshDreamland which version of the shape drawing functions do you want though? Which looks cleanest?

I also have a separate question, I need help cleaning up screen_redraw, because it too has become unwieldy maintaining all these different versions. My question is just why we've always drawn the particles implementation twice:
https://github.com/enigma-dev/enigma-dev/blob/b4bb61b6e791ea733e3b9cb619067159adcb5151/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLscreen.cpp#L155
https://github.com/enigma-dev/enigma-dev/blob/b4bb61b6e791ea733e3b9cb619067159adcb5151/ENIGMAsystem/SHELL/Graphics_Systems/OpenGL1/GLscreen.cpp#L180

That code is from a long time ago, but now we have since extracted it into draw_insts() and draw_tiles() and I am not sure I understand why both of these functions is drawing particles. Can you please clarify and let me know which one to do delete?

**Comment by JoshDreamland** [comment]
Thanks again for cleaning this up. Every one of these big deletion pull requests is another step toward the general maintainability of this project. Go ahead and merge this whenever; you can wait for the build, but the graphics systems have already passed, so anything that fails from here is probably a flake.

**Comment by RobertBColton** [comment]
Just a note about what @faissaloo mentioned. The one use case I have found for using ``inline`` was in #1082 to silence warnings about static functions, such as ``window_handle()`` being unused. So there are still places where you may want to ``inline`` even though the C++ standard dictates that the compiler is free to ignore you.

**Pull request merged**
