### PR TITLE
Generic Surface Objects

### PR DESCRIPTION
**Pull request by RobertBColton**
This pull request is a friend of #1643 aiming to abstract commonalities of the surface objects across the graphics backends and generalize some surface functions. The approach I took this time is actually slightly different. I created a generic `enigma::BaseSurface` struct which all of the backend `enigma::Surface` structs inherit. I did not give each backend's `enigma::Surface` struct its own unique name like I did for textures. This allowed me to forward declare `enigma::Surface` and use it within the `get_surface` macro for debug error checking.

### Summary of Changes
* Created `enigma::BaseSurface` in the `General/` folder which each backend's `enigma::Surface` inherits from.
* Used the new `enigma::BaseSurface` to declare and define a generic `enigma::surfaces` vector to hold the surface objects.
* Copied the `get_surface` macro over to `General/` where it does bounds checking before casting the `enigma::BaseSurface` to `enigma::Surface`.
* Moved some surface getter functions to `General/` to eliminate duplication of code.
* Fixed a crash in the D3D9 bridge that resulted from me handling lost devices for null surfaces that have already been destroyed.
* Changed the D3D surface sources to access the `get_surface` local as a reference instead of a pointer. Josh prefers keeping the macro using a reference and not a pointer, hence why the change I made to GL was undone.

### CODE REVIEW

**Comment by JoshDreamland** [comment]
Robert, you spent so much effort changing every fucking period in this engine into a `->`... did it every occur to you that the macro used in every function in the engine could just deference the pointer? That would avoid build errors from any code you and the CI miss, such as user code in forks. I'm literally sad to come here and tell you that the hour you spent doing that was a bad thing, but I don't know what else to do. It's an ugly, brittle change.

Anyway, I should point one thing out: the only reason I don't think this is an efficiency hit is because fundies already replaced the texture struct array with a vector of fucking pointers. (Which makes it even more mysterious to me that you felt the need to replace ten thousand periods with arrows.) So if we've lost engine performance, we lost it then.

**Comment by RobertBColton** [comment]
@JoshDreamland you have to look at why I did that. We had two versions of the macro basically, D3D used pointers and GL used references. GL was actually the anomaly because nowhere else am I aware of do we use references in any of the getter macros. Further, you are undermining the fact that I actually replaced an `unordered_map`, which to you would be way worse, with a vector of pointers. Everywhere else we have used a vector of pointers for storing allocated resources.

If you no longer agree with this approach and would like it refactored as references just say so explicitly. The change did not actually require as much work as you think it did, I actually used a regular expression which took 3 seconds. I will gladly change the storage mechanism or just the getters or whatever to references if you honestly feel it's a better idea. Let me know.

**Comment by fundies** [comment]
> 
> 
> Robert, you spent so much effort changing every fucking period in this engine into a `->`... did it ever occur to you that the macro used in every function in the engine could just deference the pointer? That would avoid build errors in any code you and the CI miss, such as user code in forks. I'm genuinely sad to come here and tell you that the hour you spent doing that was a bad thing, but I don't know what else to do. It's an ugly, brittle change.
> 
> Anyway, I should point one thing out: the only reason I don't think this is an efficiency hit is because fundies already replaced the texture struct array with a vector of fucking pointers. (Which makes it even more mysterious to me that you felt the need to replace ten thousand periods with arrows.) So if we've lost engine performance, we lost it then.

Why you ranting at Robert and deriding me? You're the one who's been a pain to get and feedback from lately, You're the one who approved the pr you're crying about now. You can't just ignore what we're doing when we ask for your input and then cry afterwards. I don't know whats wrong but you aren't acting like your usual self lately.

**Comment by JoshDreamland** [comment]
@RobertBColton I am not certain where (or even if) we've lost efficiency. I'm trying to point out that I once had the engine allocating everything densely. When you allocate memory densely, the kernel fetching a page from memory fetches surrounding data, too. When you have a big 'ol pointer to pointers to pointers-o-shit, one pointer points to one page points to another points to another, and you spend all your time moving memory in and out of the cache. I don't know for sure whether this is happening in ENIGMA, but it's a direction I see us slowly taking. I believe this change is an incremental improvement over what we have, but you spent a ton of effort making the same trivial change to dozens of functions, when a macro you edited was the root cause for that change.

@fundies I'm not deriding you; I'm pointing out that you changed all our C-isms to C++-isms because they're easier to read and maintain. They're also slower.

**Comment by RobertBColton** [comment]
@JoshDreamland so can I just make the macros declare references and change gl back and then change d3d to use references instead of pointers to get you to merge this? Regarding cache friendliness, fundies has expressed interest in doing #1125 which would allow that all to be addressed in a single location.

I just want to know how I can change this pull request so you are satisfied with it. We do want the main changes of this pull request which involve have a generic surface object.

**Comment by RobertBColton** [comment]
@JoshDreamland Ok: 97a185671af5c0a00a3424325719e372c68c90d7

I went back and left the `get_surface` macro declaring a reference. Then I changed the D3D sources to use a reference instead of a pointer. The overall diff has shrunk as a result of this. Please review the pull request now.

**Comment by RobertBColton** [comment]
I know how to use a regular expression thank you very much Mr. Tightpants.

**Pull request merged**
