### PR TITLE
Fix for multi-code-block statements and exit.

### PR DESCRIPTION
**Pull request by sorlok**
Fixes https://github.com/enigma-dev/enigma-dev/issues/911

Turns this:
```
//code block 1:
exit;

//Code block 2:
show_message("HI");
```

Into this:
```
  {
    goto block_end_0;;    
  }
  block_end_0:
  {
    show_message("HI");
  }
```

Note that these block labels are only created if "exit" is called at least once inside them. If the current block level couldn't be determined (which is common in scripts, timelines, etc.) then the previous behavior of "return 0" is used. This causes scripts, timelines, etc. to act at least as accurately as they used to.

### CODE REVIEW

**Comment by sorlok** [comment]
Ok, this is ready. The compliance settings were updated, and I added "enigma_" to each block label. I think "__enigma_" is overkill, given the rarity of switch statements in GML, and the penchant developers have for type prefixing resource types (spr_hero, etc.).

**Comment by RobertBColton** [comment]
@sorlok Looks like another merge conflict, I'll need you to fix that first so I can pull and test and confirm it works then I'll merge.

**Comment by sorlok** [comment]
Fixed it.

**Comment by RobertBColton** [comment]
@sorlok I have tested and can confirm the branch works as expected and that other regressions have not appeared to pop up. Several games have been tested and confirmed to still work. So I am going to merge this and on a side note I backed up the unit test to ENIGMA's dropbox.
https://www.dropbox.com/s/neevlvh8qwejlgb/multiblock_exit.gm81?dl=0

**Comment by sorlok** [comment]
@RobertBColton Thanks for the insight! I wonder why they didn't just do a longjump (which is basically what we did) and call it a day?

**Comment by RobertBColton** [comment]
@sorlok I think they were just talking and don't actually want to fix it. Or else they are planning to break each code block into a separate method and then group them, kind of like how we group events. That way you avoid the label identifier conflicts, but then that screws up vars. So I am not really sure, I think they just don't really care to fix it.

**Comment by BPzeBanshee** [comment]
I notice ENIGMA gives error 2 when using an exit statement in Room Creation code due to using a return 0 when exit is used. GM 8.0 and Studio don't complain. http://pastebin.com/PXJxTqQW

**Comment by RobertBColton** [comment]
@BPzeBanshee Oh boy, there's not really much that can be done about that, but please file a separate ticket for the issue since this has been closed.

**Pull request merged**
