### PR TITLE
Execute Shell Return Code

### PR DESCRIPTION
**Pull request by RobertBColton**
This is for hugar. WIP

### CODE REVIEW

**Comment by RobertBColton** [comment]
@time-killer-games I don't know, I wasn't paying attention but I just wanted to show this. I think you are doing something more special than I am, these functions should obviously return the exit code. I am not talking about the return values of the command, just its exit code.

**Comment by time-killer-games** [comment]
What does he need the exit code for? I seriously doubt he needs it or even knows what it's for.

**Comment by RobertBColton** [comment]
I think you're right and that what he was trying to do, get the result of a KDialog call, won't work this way. However, that does not change the fact that people might want to get the exit code of these functions. I think it's silly that GM doesn't return it in GM8.

**Comment by time-killer-games** [comment]
I can close my other pr and let you make your own version of it if you want. I spent since *before* the crack of dawn yesterday to *after* 11pm working on It, just for Josh to tell me he doesn't like any of my code and tells me to redo it with a completely different approach, and just because Windows doesn't support a function I was using. Even though technically, Windows should be completely different code regardless so that we can have utf-8 support, but Josh was being too arrogant and fucktarded I decided to keep that important detail to myself that he somehow forgot.

**Comment by RobertBColton** [comment]
No, please don't, I didn't want to do anything but show this simple GM API can be improved.

**Comment by time-killer-games** [comment]
The return code varies between Windows and Unix based systems, which is pretty useless to most users on top of that.

**Comment by RobertBColton** [comment]
@JoshDreamland nope, ShellExecuteW returns 0 when the operating system is out of memory.
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew
ShellExecuteW Return Zero

**Pull request closed without merging**
