### PR TITLE
Fix Windows Fullscreen Toggle

### PR DESCRIPTION
**Pull request by RobertBColton**
WIP

### CODE REVIEW

**Comment by faissaloo** [comment]
Just tested this, doesn't seem to do anything for #1549

**Comment by RobertBColton** [comment]
Alright, so I think what the issue may be then is that xlib just does fullscreen different from Windows. I don't know if xlib requires that, in addition to adding or removing the atom, we resize the window to cover the screen like faux fullscreen on Windows does. This is going to be difficult to reconcile the differences between xlib and Windows here for this reason.

You could try commenting out the `enigma::compute_window_size` in xlib's `window_set_fullscreen` and just see what adding and removing the atom alone does.
https://github.com/enigma-dev/enigma-dev/blob/712a4d7e97fe7480602add58bc173f8a7e5ade9e/ENIGMAsystem/SHELL/Platforms/xlib/XLIBwindow.cpp#L443

**Comment by faissaloo** [comment]
Yeah I've already tried playing around with the atom & compute_window_size(), only made the problem worse.

**Comment by RobertBColton** [comment]
Ok, thanks. I think we should start with still pushing this through for Windows, because I am sick of it not working here too. Then I'll try to get Josh to actually poke around xlib or else try to boot a VM myself. One more thing I have to say is that, for me, this work around still seems to have the scaling issues you speak of in SDL but not in Win32. You could still also try this fix with SDL for me, because if I can also get SDL working perfectly you can temporarily build your game with that platform, if you like of course.

**Comment by time-killer-games** [comment]
My pr fixes this: https://github.com/enigma-dev/enigma-dev/pull/1831 @RobertBColton please close this along with any other pr's that would potentially break my fixes.

**Pull request closed without merging**
