### PR TITLE
Fixes compileEGMf always compiling to 32-bit rather than native.

### PR DESCRIPTION
**Pull request by faissaloo**
See:
https://github.com/enigma-dev/enigma-dev/pull/929#issuecomment-247857016

### CODE REVIEW

**Comment by TheExDeus** [comment]
You can undo that in the makefile here: https://github.com/enigma-dev/enigma-dev/blob/master/CompilerSource/Makefile#L32 . I did it because at least on Windows only 32bits work. Everything else breaks no matter how hard you try. In that branch I tried enabling 64bits for both the parser and the engine to get some performance, but as on Windows I cannot run 64bit .dll I had to force 32bits (I use MinGW64 by default, so I have to force -m32 or it compiles into 64bit mode which I cannot run).
64bit game compilation worked, but only if all the Additional/ dependencies are also 64bit. I wasn't able to recompile all of them so I didn't update them. That is one of the "todo's" I had several months back before merging that branch. But for engine 64bit compilation is a different .ey, so you should be able to change that in the settings. On Linux it might even work fine, as the dependencies are usually the same bitness as the system.

**Comment by faissaloo** [comment]
The engine is fine, it's just the compiler. How about forcing 32-bit only on Windows and just not specifying for other platforms?  
```
ifeq ($(OS), Linux)
	TARGET := ../lib$(BASE).so
	CXXFLAGS += -fPIC
	MKDIR := mkdir
else ifeq ($(OS), Darwin)
	TARGET := ../lib$(BASE).dylib
	CXXFLAGS += -fPIC
	MKDIR := mkdir
else
	TARGET := ../$(BASE).dll
        CXXFLAGS += -m32
	LDFLAGS += -static-libgcc 
	MKDIR := mkdir.exe
endif
```

**Comment by RobertBColton** [comment]
I am confused why we have to force 32 bit for Windows?

**Comment by TheExDeus** [comment]
Because 64bit's didn't work. Has anyone actually got it working? We need 32bit Java (at least it is still mentioned on the Download page) and that used 32bit jna, which in turn only worked with 32bit dll.

If any of that has changed and suddenly we can use 64bit's then go ahead and change the makefiles as needed.

**Comment by RobertBColton** [comment]
Yeah we can, I didn't know all that much about the structure of everything. But if you know how to rebuild the libs and everything then we can build a 64 bit ZIP. I think it is possible to make it both 32 bit and 64 bit. I asked you if you could do it a while ago because i never got around to it and couldn't figure it out.
https://github.com/enigma-dev/lgmplugin/issues/20

Anyway, MinGW64 can build both 32 bit and 64 bit I guess. But we need to ship both a 32 bit and a 64 bit JNA then and let the JVM pick up which one it wants to use (I think it can do this automatically). So we should leave all this forcing stuff out and whatever Java architecture you launch ENIGMA the first time with, it would load a compatible JNA, which will compile a compatible compileEGMf.dll and I don't even know if it matters what the engine is. The engine should be built based on a what the user wants, we should probably make a drop down for platforms like Visual Studio's in the lgmplugin.

**Comment by fundies** [comment]
wow cant believe josh let @TheExDeus push that through. Ofcourse 64bit works ... It may require setup on windows though

**Comment by TheExDeus** [comment]
Engine bitness can be changed inside LGM by specifying a different platform. Technically that is correct way of doing it because 32bits and 64bits do specify a platform, just like OS does. I even specified two Additional/ subdirectories in the gcc.ey and gcc64.ey so all we need is compile all the libs in both bitness.
Sadly I wasn't able to do it either - I only was able to compile 64bit zlib, because that is the only mandatory lib required for building an enigma game. I tried also to compile OpenAL, but it didn't work well because I couldn't recompile the different formats as well (flac, vorbis etc.). Maybe if I tried it now I would have better luck.

Anyway, this can be merged if 64bit java with 64bit dll works.

**Comment by JoshDreamland** [comment]
Yes, 64-bit Java should work with a 64-bit DLL on Windows. Most 64-bit systems come with a 64bit Java; the only reason we hit problems is because Robert is shipping a 32-bit MinGW in the zip he maintains. This isn't really Robert's fault; I recall MinGW64 being very inconsistent about its binutils. Getting that release to use MinGW64 or Clang is probably our best option. Especially Clang, moving forward, for obvious reasons.

**Comment by RobertBColton** [comment]
We should probably do this already to stop all the Windows people from showing up and having to tell them to install a 32 bit Java.

**Comment by RobertBColton** [comment]
I am merging this because of #1011 where it broke Mac for somebody. Applying this pull request fixed his 64 bit Java loading the 32 bit dll. We can make this change when we do the 64 bit ZIP.

**Comment by faissaloo** [comment]
@RobertBColton Because the MinGW you're using is 32-bit and I don't think a MinGW with multilib exists.

**Comment by RobertBColton** [comment]
Yeah I was getting that before this PR too though. That's why I'm confused why this is at all working for anyone else on Windows.

**Comment by fundies** [comment]
theres a 64bit mingw64 and a 32bit mingw64 but no multilib mingw64. The naming is awful.,,

**Pull request merged**
