### PR TITLE
Rename Directory Delete Function

### LINKED ISSUE #1953: directory_destroy is called directory_delete
ENIGMA has `directory_delete`, which was added to GameMaker as `directory_destroy`.
https://docs.yoyogames.com/source/dadiospice/002_reference/file%20handling/directory_destroy.html

It looks like @time-killer-games was going to fix this in #1072 and #1073 but they were never merged.

Please be aware that I am adding a test for directory_delete in #1952, which will need changed later when this is fixed.

### PR DESCRIPTION
**Pull request by RobertBColton**
This resolves #1953 by renaming the function the same as the GMS version.

@time-killer-games you ok with this?

### CODE REVIEW

**Comment by fundies** [comment]
Shouldn't you keep both (at least for a bit) in case someone was using old one? You can put a deprecated warning in old one

**Comment by time-killer-games** [comment]
Yep, that works. Thanks!

**Comment by RobertBColton** [comment]
Ok I can do that with a define, but what should the ENIGMA one be called? Leave it as it was and define the GMS one or rename it and define ours to the GMS one?

**Comment by fundies** [comment]
> Ok I can do that with a define, but what should the ENIGMA one be called? Leave it as it was and define the GMS one or rename it and define ours to the GMS one?

I don't think it matters much. IMO delete is better phraseology and is consistent with the file functions. I suggested somewhere we should make a default enabled extension for GMisms like this and draw_colour so people can maintain compatibility but also disable them if they dont need them. Also, please try to use a small function instead of a define when possible

**Comment by RobertBColton** [comment]
You mean an inline sure, and you know what we could actually make a template for this that works like a define, but without being a macro.

**Comment by fundies** [comment]
I don't think you really need a template for this but I did want to move poorly named GM functions to a compatibility extension (default on) so that we're not completely bound by yoyo's idiocy. I was also interested in creating a stubs extension (default off) where we could stub GM functions not yet implemented so it's less of a hurdle for users to get some games running in ENIGMA.

**Comment by RobertBColton** [comment]
Closing in favor of #2036.

**Pull request closed without merging**
