### PR TITLE
revert broken pr by tkg

### PR DESCRIPTION
**Pull request by fundies**
revert of #1831 as it completely broke sdl somehow

### CODE REVIEW

**Comment by time-killer-games** [comment]
@fundies my icon pr fixes this. This pr you are revertinf fixes SO MANY THINGS. You are making the engine WORSE. I'm getting josh to close this without reservations. You are doing this to be a cry baby because I told you the truth about your existence on discord and that is mostly everyone on the planet wish you never did, and again, you are less than human.

**Comment by fundies** [comment]
This commit completly broke drawing in sdl. Feel free to resubmit it after you write it properly.

**Comment by RobertBColton** [comment]
I'm sorry it has to be said that icons don't fix windowing problems. I have given this pull request my blessing out of principle. I saw that the original pull request I approved was hijacked and several unrelated changes were amended to it after the fact (I really do not appreciate abuse of my pull request reviews). That said, I'm being nice enough to get #1897 merged and will gladly offer advice when these fixes here are redone properly.

**Comment by time-killer-games** [comment]
@fundies i did write it properly. Josh is refusing to merge the changes that made it proper because he is lazy and it is a big pr. Yet your big pr's which break everything instead of fixing things he doesn't even look at or review he just gets harassed into merging like that fantastic pr you made that called show_error() modals everywhere rending the entire engine unusable.

**Comment by time-killer-games** [comment]
@RobertBColton for your info, the icon pr consists of things related to windowing as well. you already knew that, but I am saying this for the GitHub staff to know as they review my reports.

**Comment by fundies** [comment]
It was pretty clear why show_error broke your dialogs and took 30 seconds to fix. I have no idea how you broke SDL and neither do you. I'm not intrested in debugging it for you so we can revert this until you pinpoint the issue.

**Comment by time-killer-games** [comment]
@fundies I already know why it was doing that and you gave me a fix which i added to my pr. You are lying through your own teeth and this will be used against you.

**Comment by fundies** [comment]
Feel free to send an alternative PR that fixes drawing on sdl before robert merges this one and I will close this one. I really don't care how it's fixed as long as it's fixed

**Comment by time-killer-games** [comment]
It makes it hard to fix things when you aren't the only one undoing my improvements.

**Comment by fundies** [comment]
bad Your definition of improvement is odd

**Comment by time-killer-games** [comment]
I fixed that already, dumbass. Your definitely couldn't just wait for Josh to merge my other pr.

**Comment by time-killer-games** [comment]
@fundies screenshot spoiler of the video you won't watch:
Screenshot_20200307_090042

**Comment by time-killer-games** [comment]
@JoshDreamland please close this. As I demonstrated yet again as plain as the nose on your face fundies and Robert are not emotionally equipped much less mentally competent enough to work on this project at all.

**Comment by JoshDreamland** [comment]
Feel free to prepare a pull request to fix the issue. Otherwise, reverting the breakage is generally how this situation is handled.

At Google, there would be zero questions asked. That change would have been reverted immediately, and the author could re-submit the change after addressing the breakage locally.

Given how long it took for fundies to notice, however, I doubt it's that urgent to fix this. So if you want to submit the fix in a new PR, we can merge that instead.

Adding the fix into yet another mega PR isn't good enough. That just causes a new breakage when we need to roll that PR back because it breaks something different. This is why I ask you not to make so many changes in one PR. It should always be safe and easy to roll back a breaking change.

**Comment by time-killer-games** [comment]
Why revert it and break 2 of 3 platforms when you could merge it and fix all 3 @JoshDreamland you just side with them habitually not because they are right but just like fundies you are negatively biased toward me when you have no reason to be.

**Comment by time-killer-games** [comment]
@JoshDreamland just as I predicted you failed to read my posts and you refused to watch my video presentation (it is a huge joke I even had to record that shit).

**Comment by time-killer-games** [comment]
@JoshDreamland I already prepared a full pull request to fix the issue. The problem is you refused to merge, much less even review it. You are putting me in a position where you are telling me to do something I already did and refuse to merge it until I do what I already did a second time without rhyme or reason.

**Comment by time-killer-games** [comment]
Who's to say I write a second pull request and you aren't just going to make up a stupid excuse to not merge that one as well? @JoshDreamland

**Comment by time-killer-games** [comment]
@JoshDreamland I could just as easily revert this pr fundies made and call **that** revert the breakage, which is generally how it's done. Tmr erting SDL breakage resurrects the breakage of Win32 and Xlib to being unusable, which will be the next video in my youtube series, where I compare this pr with my pr in XLib and Win32. Which is greater, Josh? You can do the math, you aren't illiterate? 2 platforms broken is worse than 1. Win32 + Xlib = 2 and SDL = 1. Your welcome to connect with reality as soon as you are able.

**Comment by JoshDreamland** [comment]
Okay, if you have the PR that fixes this issue (and does nothing else), please link it and I'll have a look. Otherwise, we'll merge this one.

**Comment by time-killer-games** [comment]
@JoshDreamland for reference, literally no one on the planet would use engima with fullscreen and scaling broken like it is n this pr wit Xlib and Win32.

https://www.youtube.com/watch?v=XsRjIghXQHA

^Here's part two of my "fundies is always wrong" series. Here I show a comparison between his pull request and mine. Notice mine is a lot more correct, and his only allows for 100% window scaling which means using other fixed percents for scaling as well as keep aspect ratio and full scale are all broken, even with zero means to go fullscreen, (instead, the window is simply looks maximized sort-of, but it's still windowed mode). It is also impossible to have a non-resizable window in his pull request.

Notice my pr appears to have the same problems at first, but that isn't really the case, I just forgot to delete engima's hidden build folder before going through the build process again. After I deleted that directory, everything worked as expected in my pull request. Fullscreen actually works, maximizing and resizing can disabled optionally, and is by default, and scaling is correct, whether at 100%, 50%, or whatever fixed scale percent you may choose, and let's not forget full scale and keep aspect ratio work.

**Comment by JoshDreamland** [comment]
SDL rendering like that screenshot above is a far bigger problem than the black area outside of the game area after resizing the window. The question isn't whether the original PR did something useful. I wouldn't have merged it if it wasn't useful. But it also completely broke rendering in SDL.

If you are trying to tell me you cannot reproduce the problem, then I will merge this PR.

**Comment by time-killer-games** [comment]
@JoshDreamland did i not mention my pr fixes that but without undoing the good changes i made?

**Comment by JoshDreamland** [comment]
You mentioned you have an icon PR that fixes it. Again, not good enough. If your icon PR introduced a 
 problem of similar magnitude, rolling it back would then re-introduce this breakage. This is why we don't pile multiple changes into single commits.

**Comment by time-killer-games** [comment]
@JoshDreamland I can make a new pull request, that's not a huge problem, but i do want that icon pr merged before i get more noticable gray hairs. I find it a bit shady Robert removed his merged commit which undid changes i made, i don't even see it in commit history but the file i saw him change is WINDOWSwindow.cpp who knows how many other things like that got tampered with without me knowing https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Platforms/Win32/WINDOWSwindow.cpp

**Comment by time-killer-games** [comment]
@JoshDreamland my icon pr doesn't break anything. Did you watch my two part video series showing it works beautify on both SDL and Xlib? (I'm going to do a Win32 video next but I'm just wasting my time because you aren't watching these)

**Comment by JoshDreamland** [comment]
I know you believe it doesn't break anything, just as you believed #1831 didn't break anything.
Again, in the event that it does break something, I need rolling it back to not break anything, which will not be the case if it is our fix for this SDL problem. We should have a separate change to fix SDL *and do nothing else*.

Also, it's enormous. It touches over 40 files in some way or another. The odds of it being without side-effect are vanishingly small.

**Comment by time-killer-games** [comment]
@JoshDreamland wish granted now please close this succeeded attempt of fundies to provoke me and replace it with the correct fix found here: https://github.com/enigma-dev/enigma-dev/pull/1899

**Comment by JoshDreamland** [comment]
This was not an attempt to provoke you, but an attempt to fix the engine.

Did you test your PR? It looks as though it's going to fail to build.

**Comment by time-killer-games** [comment]
@JoshDreamland he knows what the fix was. he told me it. he pretended he didn't know as an excuse to try to revert my changes. that is called trying to provoke me. It doesn't fail locally.

**Comment by time-killer-games** [comment]
@JoshDreamland connection timed out. that's all it was https://ci.appveyor.com/project/enigma-dev/enigma-dev/builds/31314684/job/5u21mngrym606s7o

**Comment by JoshDreamland** [comment]
I wasn't looking at the AppVeyor. I was looking at how you removed the declaration of `isFullScreen`, while the next line checks ``if (!isFullScreen) {``.

**Comment by time-killer-games** [comment]
isFullscreen is a global we use throughout the engine. We don't need it declared inside a function as well. That creates conflicts.

**Comment by JoshDreamland** [comment]
I see. I'll restart the AppVeyor when it remembers how to unpack archives.

**Comment by time-killer-games** [comment]
@JoshDreamland more like you or robert canceled it. 

"Build has been cancelled by a user."

**Comment by fundies** [comment]
I've said multiple times that I will close this if you provide a non conflated or that fixes this. I was working on Android and notice you fuxed sdl. It wasn't eloborate plan to screw with you. However I will admit I might've been more inclined to investigate and send a fix instead of a revert one if you were nicer

**Comment by fundies** [comment]
Also I genuinely do not remember what the fix is. If you failed to send it in a pr by now you can't blame me for reverting your breakage

**Comment by time-killer-games** [comment]
@fundies the thing is I didnt fail to send it in a pr. I had no magical way to know 6 months later Josh was going to say doing it in the icon pr "is not good enough". Now that he finally responded to me for the first time in 6 months on this topic he annoyingly avoided altogether, I was finally able to know how to convince him to allow SDL be fixed and that meant fixing it in it's own pr. That's pretty much why I did that just now, because he actually told me what to do to convince him to do the right thing, which he should technically do regardless.

**Comment by fundies** [comment]
You say you have no way bit knowing but it's just common sense. You don't put multiple fixes in one pr and you don't put multiple features in one pr and you definitely don't put multiple fixes and multiple new features in a singular pr

**Comment by fundies** [comment]
You have this bad habit of writing a pr, getting one of us to review it and the compounding 6 other things on it. Then you try to use that past review as leverage on someone else and we end up needing to rebase the repo because you put a binary in or broke sdl or whatever

**Comment by time-killer-games** [comment]
@fundies in my view it's common sense to do the complete opposite, the more fixed/added at once, the better. it's allowing for improvement in a way that is potentially a lot quicker. Josh apparently gets intimidated by big changes so he must not really like big improvement.

**Comment by time-killer-games** [comment]
I already told you guys I wouldnt do that anymore, but I cant change the fact this icon pr was made like half a year ago iirc. I don't exactly find it necessary to gut away at that pr when it could just be merged because there are flat out no regressions from my and hugar's testing.

**Comment by fundies** [comment]
You can have 10 small prs that get merged at the same or likely even faster rate than your bone big or would be. I made about 20prs to add sdl. I had to generalize a lot of duplicate platforming code and even with me splitting it up so much things were missed in the review process. However because there were so many small prs it was easier for myself and others to bisect exactly which changes caused the issues without the need for a complete redrafting of one huge montholic pr

**Comment by time-killer-games** [comment]
@fundies your SDL pr's are what got us in this mess. Xlib and Windows had perfect windowing until you added SDL. Then I had to go back and clean up after you by fixing what you broke, which is what this pr reverts. That said, i opened the correct fix for this that doesn't break Win32 and Xlib, and it only took one line that needed changing. So there's nothing else really to talk about and this can be closed. https://github.com/enigma-dev/enigma-dev/pull/1899

**Comment by fundies** [comment]
Xlib had issues before sdl. I did worsen windows though. If I had made a singular pr it would've had the same breakage but we woulda been forced to revert the whole thing rather than the one change that broke it. A pr that "removes duplicate computewindowsize" is much clearer than an "adds sdl" commit that changes 500 other things in addition to adding sdl

**Comment by fundies** [comment]
I will check 1899 when I get home tonight but that is where the or belongs not is some icon nonsense

**Comment by time-killer-games** [comment]
Thank you for being so gracious despite my hard-headedness. I was very quick to hit the panic button and I really thought you guys were teaming up to undo a lot of my work. I let the github staff know it was a false alarm. If anything, I'm going to be banned for being so disrespectful on this pr specifically.

**Comment by fundies** [comment]
closing in favor of #1899. Also, unblock me so I can comment there you twat.

**Comment by time-killer-games** [comment]
ween.

**Pull request closed without merging**
