### PR TITLE
Fractional Math Fixes & Test

### PR DESCRIPTION
**Pull request by RobertBColton**
This pull request originally addressed the issues raised in #620 before we switched PRNGs to not use frac at all. Now this pull request is just template-enabling frac/radian/degree math functions and expanding the math unit test to cover them.

With this change, `frac` will correctly infer the type of its arguments, `double` in the case of `random`. As Josh clarifies in #620, `double` should be used because the values used in `random` are "too large to fit in a float but too small to randomize a long".

### CODE REVIEW

**Comment by fundies** [comment]
@JoshDreamland @RobertBColton why hasnt this been merged yet?

**Comment by RobertBColton** [comment]
@fundies because Josh won't tell me why it fails Travis.

**Comment by RobertBColton** [comment]
There I pulled master to see if maybe it was fixed. Otherwise, if that don't work, try changing the float stuff to epsilon equals.

@fundies originally this was just to fix Harri's issue, but once we switched to Rusky's random that's compatible with GM, we stopped using the Mersenne Twister which this was affecting.

**Comment by fundies** [comment]
josh's macros don't like the f/L on end of numbers it looks like. you could just use casts instead of literals. or bitch at josh.

**Comment by RobertBColton** [comment]
Right, but #1795 more important to first though at the moment. This isn't stopping any game from building, but his string regression is stopping two games.

**Comment by RobertBColton** [comment]
And I can't understand why we codegen two different versions of scripts either. That's mainly what I need an answer to first if I am going to fix it.

**Pull request closed without merging**
