### PR TITLE
fix asan vertex leaks

### PR DESCRIPTION
**Pull request by fundies**

### CODE REVIEW

**Comment by RobertBColton** [comment]
Shouldn't you just be using AssetArray?

**Comment by fundies** [comment]
not really trying to refactor, Just wanted to get rid of our existing leaks quickly so I can tur asan on on the ci

**Comment by RobertBColton** [comment]
Really they aren't leaks though, the OS knows how to clean it up.

**Comment by fundies** [comment]
doesn't matter asan doesnt like you cutting corners

**Comment by RobertBColton** [comment]
I know, I was just saying.

**Comment by fundies** [comment]
takes 3 seconds to make it unique_ptr so easiest to just appease asan

**Comment by RobertBColton** [comment]
Try AssetArray it's just as simple.

**Comment by fundies** [comment]
not intrested

**Comment by fundies** [comment]
can merge. I got other leaks to plug

**Pull request merged**
