### PR TITLE
noexcept std::filesystem

### PR DESCRIPTION
**Pull request by time-killer-games**
fuck joo bitch !!!!

### CODE REVIEW

**Comment by time-killer-games** [comment]
This code doesn't do anything different from what is already in master with the POSIX and Win32 only this uses the std::filesystem. I don't understand why we need security measures for std::filesysttem but not for POSIX/win32 file manipulation because it is just using a different api to accomplish the same exact thing.

I'm happy to add security measures but that was not the point of this pr. It was to get rid of platform-specific POSIX and Win32 code. I'd like to make that a different pull request, and not really make that pull request at all until we add a proper means to turn off the sandbox.

This code isn't anymore dangerous than what we already have in the engine right now, not even by 1%.

**Comment by fundies** [comment]
> This code doesn't do anything different from what is already in master with the POSIX and Win32 only this uses the std::filesystem. I don't understand why we need security measures for std::filesysttem but not for POSIX/Win32 file manipulation because it is just using a different api to accomplish the same exact thing.
> 
> I'm happy to add security measures but that was not the point of this pr. It was to get rid of platform-specific POSIX and Win32 code. I'd like to make that a different pull request, and not really make that pull request at all until we add a proper means to turn off the sandbox.
> 
> This code isn't anymore dangerous than what we already have in the engine right now, not even by 1%. I even went ahead and used fs::remove instead of fs::remove_all so only empty directories can be deleted, which is what we have going on allowed in the engine already just like everything else.

I wasn't arguing that yours is any more dangerous, my point is that while you're rewriting it all is a good time to secure these as well as to add some tests.

**Comment by time-killer-games** [comment]
lol, ok good, I'm glad that's the case. You had me worried for a minute there. My only opposition with adding the security measures right now is that it will break existing games. If we waited until the sandbox could be turned off, then people could turn the sandbox on exclusively for their bug report reproducible examples, while not messing up their complete games, which some of them are going to be ported over from GameMaker, and having a sandbox not optional even for a temporary time won't be very convenient. People will spend time trying to make their project work with the enigma sandbox just to find out it's getting removed again with a tickbox in the IDE. For these reasons given, I think it would be better if we waited on that.

**Comment by time-killer-games** [comment]
@fundies i removed directory_delete(). we initially added that because GameMaker used to not have a function for deleting directories so we made our own. Then yoyo added it in Studio and called it directory_destroy(). Should I make a function wrapping director_destroy() so that projects using directorty_delete(() won't break or should I keep it how it is removing directory_delete in favor of directory_destroy() for a GM compatible function only.

**Comment by fundies** [comment]
> lol, ok good, I'm glad that's the case. You had me worried for a minute there. My only opposition with adding the security measures right now is that it will break existing games. If we waited until the sandbox could be turned off, then people could turn the sandbox on exclusively for their bug report reproducible examples, while not messing up their complete games, which some of them are going to be ported over from GameMaker, and having a sandbox not optional even for a temporary time won't be very convenient. People will spend time trying to make their project work with the enigma sandbox just to find out its getting removed again with a tickbox in the IDE. For these reasons given, I think it would be better if we waited on that.
> 
> If I'm going to add tests, I'll need to chat in realtime on hangouts with Josh about that so he can tell me the ins and outs for that. I do think it is better I learn to do tests sooner than keep on putting that off every day. I 100% agree I should do that at this point.

You can add security measures without breaking games. I suggest something like this:

```cpp
std::map<std::filesystem::path, bool> allowed paths = {"~/.enigma" };

bool fs_access_allowed(fs::path) {
  if (!map.contains(path)) { result = show_dialog("you allow access to derp?") map[path] = result; }
  if (map[path] == false) { DEBUG_MESSAGE("permission denied"); }
  return map[path];
}
```

As for tests, If you look at the ones we have and know how to run emake it should be rather easy to write some.

**Comment by fundies** [comment]
> > lol, ok good, I'm glad that's the case. You had me worried for a minute there. My only opposition with adding the security measures right now is that it will break existing games. If we waited until the sandbox could be turned off, then people could turn the sandbox on exclusively for their bug report reproducible examples, while not messing up their complete games, which some of them are going to be ported over from GameMaker, and having a sandbox not optional even for a temporary time won't be very convenient. People will spend time trying to make their project work with the enigma sandbox just to find out its getting removed again with a tickbox in the IDE. For these reasons given, I think it would be better if we waited on that.
> > If I'm going to add tests, I'll need to chat in realtime on hangouts with Josh about that so he can tell me the ins and outs for that. I do think it is better I learn to do tests sooner than keep on putting that off every day. I 100% agree I should do that at this point.
> 
> You can add security measures without breaking games. I suggest something like this:
> 
> ```c++
> std::map<std::filesystem::path, bool> allowed paths = {"~/.enigma" };
> 
> bool fs_access_allowed(fs::path) {
>   if (!map.contains(path)) { result = show_dialog("you allow access to derp?") map[path] = result; }
>   if (map[path] == false) { DEBUG_MESSAGE("permission denied"); }
>   return map[path];
> }
> ```
This would prompt you once per run to access specific files but all games would still work

> 
> As for tests, If you look at the ones we have and know how to run emake it should be rather easy to write some.

**Comment by time-killer-games** [comment]
By breaking games I do include the fact this will ruin user experience for finished games. You are free to do this in your own pr after Josh merges this one. I don't want to be responsible for people complaining, and I'd rather them blame the person who actually insisted on this idea, not me.

@JoshDreamland this one is ready when you are.

**Comment by fundies** [comment]
I will review / merge this if you write a test suite. Or you can wait on josh if you prefer

**Comment by time-killer-games** [comment]
Yeah I actually forgot I said I would do that. I have a look at our current CI tests right now and see if I can make enough sense of it to get it done.

**Comment by RobertBColton** [comment]
@time-killer-games ENIGMA should not do instance creation ordering or provide that as a feature, it's arguably a bad thing. You should not design your game in a way that instances depend on other instances being created first. That creates a hard dependence which can make it more difficult to refactor your project down the road. I don't really know why YoYoGames went overboard on that one. It's not even possible in other engines, like Unity3D where the start execution order is non-deterministic, and yet those engines are just fine. You want to do [loose coupling](https://en.wikipedia.org/wiki/Loose_coupling) of components in your game.

**Comment by time-killer-games** [comment]
@RobertBColton what game are you referring to that does this exactly? Last I checked none of my games are dependent on that. If they were, they wouldn't look right in Studio.

**Comment by RobertBColton** [comment]
@time-killer-games Hey woah, you're going way overboard 🏴‍☠️

No, the instance creation ordering would actually be the simplest thing to accomplish. The layering is actually going great because we have some innovation over GMS which just plagiarized Tiled anyway. I wasn't referring to any of your specific games, just happened to run into creation ordering again examining the new room editor behavior. I've been staunchly opposed to it for a while, for good reason, and I want to warn everybody why it's bad. I'm not saying it can't be added for compatibility, but that it should be hidden away. It's almost as bad as using instance ids rather than names in your code, even though both are still supported.

**Comment by time-killer-games** [comment]
@RobertBColton thank you for the clarification lel

**Comment by time-killer-games** [comment]
@fundies i added a filesystem simple test now does the CI detect it automatically or how do I make it recognize it now that I've written it?

**Comment by fundies** [comment]
> @fundies i added a filesystem simple test now does the CI detect it automatically or how do I make it recognize it now that I've written it?

Yes it will run "simple tests" automatically. You can see in the log of the azure job:

[  FAILED  ] SimpleTests/SimpleTestHarness.SimpleTestRunner/6, where GetParam() = "CommandLine/testing/SimpleTests/file_input_output.sog"
[  FAILED  ] SimpleTests/SimpleTestHarness.SimpleTestRunner/7, where GetParam() = "CommandLine/testing/SimpleTests/filesystem.gmx"

You broke one test and are failing your own.

**Comment by time-killer-games** [comment]
> > @fundies i added a filesystem simple test now does the CI detect it automatically or how do I make it recognize it now that I've written it?
> 
> Yes it will run "simple tests" automatically. You can see in the log of the azure job:
> 
> [ FAILED ] SimpleTests/SimpleTestHarness.SimpleTestRunner/6, where GetParam() = "CommandLine/testing/SimpleTests/file_input_output.sog"
> [ FAILED ] SimpleTests/SimpleTestHarness.SimpleTestRunner/7, where GetParam() = "CommandLine/testing/SimpleTests/filesystem.gmx"
> 
> You broke one test and are failing your own.

Where are you gettting that information from? I don't see it under travis.

**Comment by time-killer-games** [comment]
@fundies halp

**Comment by fundies** [comment]
> @fundies halp

It's undet the azure (test harness) log

**Comment by time-killer-games** [comment]
"Build not found"
https://dev.azure.com/enigma-dev/ENIGMA/_build/results?buildId=3419&view=logs&jobId=b104f7c4-1a4b-5abc-d67e-4b99004b8ecf

**Comment by fundies** [comment]
close and reopen pr maybe it expired

**Comment by time-killer-games** [comment]
@fundies i don't know anything about your android export so you'd either would need to tell me how to get that portion passing or you can commit to this pr yourself, whichever you prefer.

**Comment by fundies** [comment]
> @fundies i don't know anything about your android export so you'd either would need to tell me how to get that portion passing or you can commit to this pr yourself, whichever you prefer.

not all of std::filesystem is implemented on android yet so you can just block anything causing error out with #ifndef __ANDROID__ or whatever

**Comment by time-killer-games** [comment]
@fundies from the look of those errors, they haven't implemented barely anything (if anything) it doesn't recognize weakly_canonical, copy, rename, directory_iterator, temp_directory_path, current_path, so if what you say is to be applied to the current errors, i guess we can just take android support out completely at this rate. I have a feeling at least some of that is implemented, the android build is missing a compiler or linker flag of some kind, but i have no idea where any of that is set up.

**Comment by fundies** [comment]
> @fundies from the look of those errors, they haven't implemented barely anything (if anything) it doesn't recognize weakly_canonical, copy, rename, directory_iterator, temp_directory_path, current_path, so if what you say is to be applied to the current errors, i guess we can just take android support out completely at this rate. I have a feeling at least some of that is implemented, the android build is missing a compiler or linker flag of some kind, but i have no idea where any of that is set up.

I don't know much more than you. Last I checked only some of std::filesystem was implemented in android. You can try upgrading the ndk version maybe they fixed it IDK. You're going to have to do some research yourself. Hugar should know how to build for android id you need help setting it up.

**Comment by fundies** [comment]
I pushed some changes that might help you to master. You can undo the changes I made here and merge master and I think the android job should build

**Comment by time-killer-games** [comment]
@JoshDreamland @fundies would it be better if I moved the std::filesystem-based gml/edl functions from Universal to shared? If in shared, we could use them in more places and it would be less limiting I'd say, but I wanted your approval before making that decision. I don't know whether you'll agree so based on that I will act accordingly.

**Comment by fundies** [comment]
> @JoshDreamland @fundies would it be better if I moved the std::filesystem-based gml/edl functions from Universal to shared? If in shared, we could use them in more places and it would be less limiting I'd say, but I wanted your approval before making that decision. I don't know whether you'll agree so based on that I will act accordingly.

Shouldn't need them in shared the std:: versions are simple enough. Tha aside, if you can get this passing the CI I think we can merge this.

**Comment by time-killer-games** [comment]
@fundies the ci appears to be having issues again, so I guess it'll have to wait until that gets sorted out

**Comment by fundies** [comment]
> @fundies the ci appears to be having issues again, so I guess it'll have to wait until that gets sorted out

The travis bit is bugged but the test harness is failing because of your code

**Pull request closed without merging**
