### PR TITLE
Fix DirectSound Error Messages

### PR DESCRIPTION
**Pull request by time-killer-games**

### CODE REVIEW

**Comment by time-killer-games** [comment]
@RobertBColton ready for review.

**Comment by time-killer-games** [comment]
@JoshDreamland i have a feeling Robert is too upset with me to want to review this. So if you could, I'd appreciate it.

**Comment by RobertBColton** [comment]
Yeah it'd be cool to know why we're actually changing sleep. Seems the change to DirectSound is ok, and fixes run mode for me. Good job not telling me why sleep was changed though.

**Comment by time-killer-games** [comment]
@RobertBColton It's because travis doesn't like the other method we used for sleep. Ask fundies for more details, I'm not the one who wrote this code, I copied it from what fundies gave me, because he told me to do this. If anyone knows the full story as to why sleep was changed, I'm not the guy to ask.

**Comment by RobertBColton** [comment]
Revert the part about sleep for now, make that a second pull request. I'll approve this one immediately for the DirectSound fix.

**Comment by time-killer-games** [comment]
@RobertBColton i tested it locally and the change is correct, I recommend you testing it yourself before asking me to undo the whole main point of this pr.

**Comment by RobertBColton** [comment]
I did not ask you to undo it, I asked you to split it into its own pull request. Nobody has told me how to test the sleep changes and I don't feel like it at the moment. I've already tested the DSound portion of it and that's all I feel like doing right now.

**Comment by time-killer-games** [comment]
Ok, but it's a waste of time for me.

**Comment by time-killer-games** [comment]
@RobertBColton thanks, your majesty

**Pull request merged**
