### PR TITLE
Fix for exit in various room and room-instance creation code blocks.

### PR DESCRIPTION
**Pull request by sorlok**
This fixes https://github.com/enigma-dev/enigma-dev/issues/924

### CODE REVIEW

**Comment by RobertBColton** [comment]
@sorlok For reference GM: Studio also allows return 0; in the room editor creation code. I wanted to let you know this first, I have not yet tested your pull request, so this does not fully resolve the issue. Do you have any other ideas? I'll ask @JoshDreamland to weigh in.

**Comment by JoshDreamland** [comment]
I believe the simpler fix is just to not have that code return void. In GM, `return 0;` in room creation code will work fine.

**Comment by sorlok** [comment]
Sounds fine to me. I'll push a fix with that instead.

**Comment by sorlok** [comment]
Made a pull request that implements this:
https://github.com/enigma-dev/enigma-dev/pull/926

**Pull request closed without merging**
