### PR TITLE
Compiler Cleanup: Remove more global state, fix alarms

### PR DESCRIPTION
**Pull request by JoshDreamland**
Some global state wasn't being updated because I cut a bunch of it out, deleted a redundant copy of some code, and lost a little information in the process. The alarms fix was really just updating the enigma_namespace global. Instead of doing that, I've removed the enigma_namespace global. Good fucking riddance.

There's still some more global state lying around, and ENIGMA is passing around JDI definition pointers willy-nilly, which it should NOT be doing. That's entirely my fault, but it still hurts the same.

In the future, we'll want to pull out the JDI definitions from the compiler. But the only occurrences of JDIisms, now, are within lang_CPP, the syntax checker, and the code translation / "linking" module. The syntax checker and code translation unit are going to be replaced by a tree builder and pretty printer, respectively. When this occurs, I intend to abstract away the process of symbol definition (checking if a function exists, checking if it's variadic, etc). The linking module will only need minor tweaks. It's actually pretty brilliant for young me; I'm impressed.

### CODE REVIEW

**Comment by RobertBColton** [comment]
I don't why but this branch gives me the following error with the Mark Overmar's fps6 GMK. I can send this to you, but it also happens to be available on the EDC.

Download FPS GMK: [fps.zip](https://github.com/enigma-dev/enigma-dev/files/2806395/fps.zip)

```cpp
 obj_wall_basic: 1 events:
  Event[8, 0] Check `obj_wall_basic::draw...{ { if ( point_distance ( x , y , global . ; camx , global . ; camy ) > 240 ) ; exit ; d3d_draw_wall ( x1 , y1 , z1 , x2 , y2 , z2 , tex , 1 , 1 ) ; }  Done. Parse...Thread-5:
java.lang.Error: Invalid memory access
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:383)
        at com.sun.jna.Function.invoke(Function.java:315)
        at com.sun.jna.Library$Handler.invoke(Library.java:212)
        at com.sun.proxy.$Proxy0.compileEGMf(Unknown Source)
        at org.enigma.EnigmaRunner$CompilerThread.run(EnigmaRunner.java:664)
```

**Comment by RobertBColton** [comment]
Here, I got you a GDB stack trace when emake crashes on building the FPS game.

```
 obj_wall_basic: 1 events:
  Event[8, 0] Check `obj_wall_basic::draw...{ { if ( point_distance ( x , y , global . ; camx , global . ; camy ) > 240 ) ; exit ; d3d_draw_wall ( x1 , y1 , z1 , x2 , y2 , z2 , tex , 1 , 1 ) ; }  Done. Parse...[Thread 9784.0x50a4 exited with code 0]
[Thread 9784.0x668 exited with code 0]
[Thread 9784.0x24f4 exited with code 0]
[Thread 9784.0x41d0 exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000002e1cf34 in lang_CPP::referencers_varargs_at (this=0x15cc250,
    refs=...) at compiler/jdi_utility.cpp:61
61        if (refs.top().type != ref_stack::RT_FUNCTION)
(gdb) bt
#0  0x0000000002e1cf34 in lang_CPP::referencers_varargs_at (this=0x15cc250,
    refs=...) at compiler/jdi_utility.cpp:61
#1  0x0000000002e712fd in lang_CPP::referencers_varargs (
    this=<optimized out>, refs=...) at ./languages/lang_CPP.h:80
#2  0x0000000002dc1ea3 in language_adapter::is_variadic_function (d=
    0x6b32c20, this=0x15cc250) at ./languages/language_adapter.h:95
#3  language_adapter::is_variadic_function (d=0x6b32c20, this=0x15cc250)
    at ./languages/language_adapter.h:95
#4  parser_ready_input (code=..., synt=..., strc=<optimized out>,
    strc@entry=@0x7b72618: 0, string_in_code=...)
    at parser/parser_components.cpp:164
#5  0x0000000002da8135 in parser_main (code=..., pev=pev@entry=0x7b725d0,
    script_names=..., isObject=isObject@entry=false) at parser/parser.cpp:171
#6  0x0000000002e35a77 in lang_CPP::compile_parseAndLink (
    this=<optimized out>, game=..., state=...)
    at C:/msys64/mingw64/include/c++/8.2.1/bits/basic_string.h:936
#7  0x0000000002e1f837 in lang_CPP::compile (this=this@entry=0x15cc250,
    game=..., exe_filename=exe_filename@entry=0xcff5d0 "/tmp/test.exe",
    mode=mode@entry=1) at compiler/compile.cpp:336
#8  0x0000000002e1de95 in compileEGMf (es=<optimized out>,
    exe_filename=0xcff5d0 "/tmp/test.exe", mode=1) at compiler/compile.cpp:161
#9  0x0000000000451a03 in std::_Function_handler<int (EnigmaStruct*, char const*, int), int (*)(EnigmaStruct*, char const*, int)>::_M_invoke(std::_Any_data const&, EnigmaStruct*&&, char const*&&, int&&) (__functor=...,
    __args#0=@0xcff148: 0x766d1c0,
    __args#1=@0xcff150: 0xcff5d0 "/tmp/test.exe", __args#2=@0xcff158: 1)
    at C:/msys64/mingw64/include/c++/8.2.1/bits/std_function.h:282
#10 0x00000000004482c9 in std::function<int (EnigmaStruct*, char const*, int)>::operator()(EnigmaStruct*, char const*, int) const (this=0xcff650,
    __args#0=0x766d1c0, __args#1=0xcff5d0 "/tmp/test.exe", __args#2=1)
    at C:/msys64/mingw64/include/c++/8.2.1/bits/std_function.h:687
#11 0x000000000040f036 in EnigmaPlugin::BuildGame (this=0xcff630, data=
    0x89556d0, mode=emode_debug, fpath=0xcff5d0 "/tmp/test.exe")
    at EnigmaPlugin.cpp:126
#12 0x000000000040d172 in main (argc=11, argv=0x1768b90) at Main.cpp:131
(gdb)
```

**Comment by JoshDreamland** [comment]
Fascinating... there is exactly no reason this should not have been happening before. I've pushed a correction.

**Comment by RobertBColton** [comment]
You've fixed the regression with the coins/alarms from #1514 in SONIGMA.

**Pull request merged**
